Update setup.md
RikkaApps/websites pull request #79
Opened 2023-06-12 03:57 UTC by e-t-l

Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2023-06-15 14:07 UTC, farshadjanu1 approved these changes

2023-06-17 15:53 UTC, e-t-l commented
GOS adds this setting to the main Settings > Security page. It's very obvious and presumably anyone who goes to the trouble of installing GOS knows where/what it is, or is savvy enough to do a search for it.

So would an acceptable amendment be:
> The Security setting "Secure app spawning"...

?

2023-06-21 07:14 UTC, Kuku425 approved these changes

2023-06-21 07:15 UTC, Kuku425 approved these changes

2023-06-21 14:08 UTC, e-t-l commented
I made the described change. Pls let me know if it needs more detail (or feel free to edit the phrasing as you see fit). This is where the setting is:
![Screenshot_20230615-122437_1](https://github.com/RikkaApps/websites/assets/40775958/1d2fdfe3-973a-4b63-8360-ae3883c11910)
So it's pretty straightforward.

2023-06-21 15:49 UTC, merged

2023-07-07 04:48 UTC, gamemedia81 approved these changes
- [ ]

2023-07-08 06:09 UTC, Belu-momhn commented
**By shizuku **
Here:
![images (1)](https://github.com/RikkaApps/websites/assets/133125035/b7e365fb-504a-4380-b27b-7d0bcb929c92)

Trwp : no
Orangefox : no

2023-07-08 06:12 UTC, Belu-momhn commented
> 1 `adb devices` termux or windows command prompt
> 2 `adb (path) ` Enter
> 3 `adb (path) cmd -l` Enter

Done!

2023-07-08 06:17 UTC, Belu-momhn commented
> errors shizuku or install recovery power 
> Clear follow or walk or is or adb

Done!

2023-09-27 19:28 UTC, Jaswant1010 approved these changes

2023-11-06 00:54 UTC, sebael reviewed
shizuku/guide/setup.md

2023-11-07 11:58 UTC, Bayi321 commented
Apk stupid

2023-11-27 23:34 UTC, Edgarhsl approved these changes

2024-01-20 17:36 UTC, EzraDechwong0 approved these changes

2024-01-20 20:46 UTC, EzraDechwong0 approved these changes

2024-01-29 12:44 UTC, AceMentura reviewed
e-t-l:patch-1

2024-01-29 12:45 UTC, AceMentura reviewed
shizuku/guide/setup.md

2024-01-30 21:43 UTC, AceMentura approved these changes

2024-02-05 06:53 UTC, LM1LC3N7 commented
For the records, DivestOS (a soft fork of LimageOS  with patches from GrapheneOS) also has the same option. 

Shizuku also stops but as I am starting it using the WiFi adb and then shut down my WiFi when moving outside, I suspect this kills the adb session used by shizuku. As I read it somewhere on the issues in that repo.

2024-03-19 19:45 UTC, YunsKhaild99 commented
Hi there 👋 I have a new phone and I

2024-04-09 09:58 UTC, Kirtjohn81 approved these changes

2024-04-10 21:17 UTC, rannlangel commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
e-t-l:patch-1

2024-04-11 03:57 UTC, Bombay268 commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
evilscoincom.wordpress.com
(s’ouvre dans un nouvel onglet)

2024-04-11 03:57 UTC, Bombay268 commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
evilscoincom.wordpress.com

2024-04-19 17:20 UTC, Skizzels commented on shizuku/guide/setup.md
> +Note: GrapheneOS is not an officially supported ROM, but as of January 2023 Shizuku will run on it.
Ok

2024-04-19 18:15 UTC, ousmanali4455 commented
Not work VoLTE provision

2024-04-19 18:17 UTC, ousmanali4455 commented
![IMG_20240419_211641](https://github.com/RikkaApps/websites/assets/167351473/67fa48f2-629f-4cb9-8241-93da627d2b8a)
Not open VoLTE or other services

2024-04-20 09:26 UTC, Earlycrusher commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2024-05-02 12:55 UTC, HYPYost approved these changes

2024-05-07 01:02 UTC, Kboxoxx approved these changes

2024-05-10 11:42 UTC, Screwylou commented on shizuku/guide/setup.md
Llugert7

2024-05-16 08:45 UTC, Playmore00 approved these changes

2024-05-16 08:55 UTC, jeyms233 commented on shizuku/guide/setup.md
> +Note: GrapheneOS is not an officially supported ROM, but as of January 2023 Shizuku will run on it.
> Ok

2024-05-20 02:00 UTC, Kensiosort reviewed
🤭

2024-05-20 05:02 UTC, Bolshau approved these changes

2024-05-20 05:58 UTC, Definitionist approved these changes

2024-05-20 06:01 UTC, Bolshau approved these changes

2024-05-20 06:02 UTC, Bolshau approved these changes

2024-05-20 06:02 UTC, Bolshau approved these changes

2024-05-20 06:32 UTC, Bolshau approved these changes

2024-05-21 07:25 UTC, bokssssss commented on shizuku/guide/setup.md
> +The Security setting "Secure app spawning" may need to be disabled.
shizuku/guide/setup.md

2024-05-21 22:50 UTC, Zuly2 commented
[log.txt](https://github.com/RikkaApps/websites/files/15396068/log.txt)
[text.txt](https://github.com/RikkaApps/websites/files/15396069/text.txt)

2024-05-21 22:51 UTC, Zuly2 commented
gh pr checkout 79

2024-05-24 20:38 UTC, Alfredgarcia4 approved these changes

2024-05-24 21:43 UTC, Alfredgarcia4 approved these changes

2024-05-24 22:07 UTC, Bolshau approved these changes

2024-05-25 12:31 UTC, Kboxoxx approved these changes

2024-05-25 12:40 UTC, bokssssss commented
e-t-l:patch-1

2024-05-25 12:40 UTC, bokssssss commented
e-t-l:patch-1

2024-05-25 12:40 UTC, bokssssss commented
Hello

2024-05-25 14:21 UTC, Kboxoxx commented on shizuku/guide/setup.md
> +The Security setting "Secure app spawning" may need to be disabled.
> shizuku/guide/setup.md

2024-05-26 02:56 UTC, Screwylou commented on shizuku/guide/setup.md
Lo

2024-05-26 10:02 UTC, Kboxoxx approved these changes

2024-05-30 03:42 UTC, hamoodismail reviewed
Jameel noori nastaliq

2024-05-31 06:30 UTC, mkmk452487449 commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2024-05-31 21:25 UTC, 242045lanm commented on shizuku/guide/setup.md
> +The Security setting "Secure app spawning" may need to be disabled.
shizuku/guide/setup.md

2024-06-04 05:56 UTC, 0959285481 commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
O

2024-06-06 06:08 UTC, Rishidash80 commented
Gd app

2024-06-06 06:08 UTC, Rishidash80 commented
Good app

2024-06-06 06:08 UTC, Rishidash80 commented
[websites-master.zip](https://github.com/user-attachments/files/15604506/websites-master.zip)

2024-06-10 05:27 UTC, JessiG2319 approved these changes

2024-06-15 14:45 UTC, Episyah approved these changes

2024-06-15 20:13 UTC, XiaomiTpro approved these changes

2024-06-16 10:09 UTC, thereal4dub reviewed
shizuku/guide/setup.md

2024-06-17 20:01 UTC, Hourmafia707 commented
> Graphene
172.18.11.218:45299

2024-06-20 05:52 UTC, Jessej9holloway approved these changes

2024-06-21 17:56 UTC, Thuanui commented
Adb bị hạn chế

2024-06-21 17:58 UTC, Thuanui reviewed
adb bị hạn chế

2024-06-23 22:09 UTC, JesusG24 approved these changes

2024-06-24 22:03 UTC, Scratch-S approved these changes

2024-06-29 00:48 UTC, Stealth188 reviewed
Patch

2024-06-29 00:48 UTC, Stealth188 commented on shizuku/guide/setup.md
> +#### GrapheneOS
153

2024-07-02 12:30 UTC, Alfredgarcia4 commented on shizuku/guide/setup.md
Grax

2024-07-03 07:54 UTC, Stealth188 reviewed
shizuku/guide/setup.md

2024-07-04 04:47 UTC, Cordero19 approved these changes

2024-07-11 01:37 UTC, Johnismaiel approved these changes

2024-07-11 01:38 UTC, Johnismaiel approved these changes

2024-07-19 01:17 UTC, R0nni333 approved these changes

2024-07-22 00:16 UTC, ALSEDD01 approved these changes

2024-07-22 00:17 UTC, ALSEDD01 approved these changes

2024-07-27 10:26 UTC, Mauricio-sy commented on shizuku/guide/setup.md
> +
X favor

2024-08-01 18:59 UTC, nares2024 requested changes
shizuku/guide/setup.md

2024-08-01 18:59 UTC, nares2024 commented on shizuku/guide/setup.md
> +The Security setting "Secure app spawning" may need to be disabled.
shizuku/guide/setup.md

2024-08-05 01:10 UTC, Najim-jpj reviewed
https://github.com/RikkaApps/websites.git

2024-08-05 21:35 UTC, DUONGANHTANTAI approved these changes

2024-08-08 02:03 UTC, mlpmlpmlo commented
> I made the described change. Pls let me know if it needs more detail (or feel free to edit the phrasing as you see fit). This is where the setting is: ![Screenshot_20230615-122437_1](https://private-user-images.githubusercontent.com/40775958/247577072-1d2fdfe3-973a-4b63-8360-ae3883c11910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODI4OTksIm5iZiI6MTcyMzA4MjU5OSwicGF0aCI6Ii80MDc3NTk1OC8yNDc1NzcwNzItMWQyZmRmZTMtOTczYS00YjYzLTgzNjAtYWUzODgzYzExOTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAyMDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyY2Y2YmY2MzgzYjM5YzQ3NzFjZGE4MjRmYjYyNWMyYTEzY2QwYmE4NzI1MTIxOTljYWU1ZmRhNWY4ODllMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92iH43xpTGE4FUuX5esUKjoFSLz1Gez_df7NQyO3sxU) So it's pretty straightforward.

https://github.com/RikkaApps/websites/pull/79#issuecomment-1600908117

2024-08-08 02:05 UTC, Jessej9holloway commented
Thank you very much that was very very helpful

2024-08-10 06:01 UTC, Qdamwowo requested changes
Fix it

2024-08-15 19:34 UTC, Playmore00 reviewed
shizuku/guide/setup.md

2024-08-17 06:16 UTC, Zero4440 approved these changes

2024-08-17 15:20 UTC, Leyla62862 commented
e-t-l:patch-1

2024-08-17 15:21 UTC, Leyla62862 commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2024-08-17 15:21 UTC, Leyla62862 commented
adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/start.sh

2024-08-17 17:18 UTC, Playmore00 approved these changes

2024-08-19 10:01 UTC, Deymon13 approved these changes

2024-08-19 10:04 UTC, Deymon13 commented on shizuku/guide/setup.md
> +#### GrapheneOS
Me ayuda por favor

2024-08-22 22:36 UTC, Unconnecte approved these changes

2024-08-22 22:36 UTC, Unconnecte approved these changes

2024-08-23 08:40 UTC, Playmore00 approved these changes

2024-08-23 15:24 UTC, Ajit761 commented
90fps

2024-08-27 10:32 UTC, jeromin10 approved these changes

2024-08-28 16:05 UTC, Poetic29 approved these changes

2024-08-31 21:44 UTC, kennicole commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2024-09-02 18:37 UTC, luqmandaut commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2024-09-03 06:15 UTC, Marcoslpez99 approved these changes

2024-09-12 09:03 UTC, dkdjsbsb commented
نن

2024-09-13 18:04 UTC, dkdjsbsb commented
ع

2024-09-19 15:09 UTC, Anghelgwapo commented
Ueuejejehjejejejeieieiejejejejekdkdidodldkdkdkdkskskskskskkssksks

2024-09-23 20:19 UTC, Darker69461 approved these changes

2024-09-23 20:20 UTC, Darker69461 approved these changes

2024-09-30 15:01 UTC, dasejunejonadeem commented
Hi shezo

2024-09-30 15:01 UTC, dasejunejonadeem reviewed
34175340

2024-10-05 01:01 UTC, Talhasaleem110 approved these changes

2024-10-06 05:42 UTC, binhle113 approved these changes

2024-10-09 05:13 UTC, binhle113 approved these changes

2024-10-24 21:57 UTC, Wadeziggg commented
Well

2024-10-24 21:57 UTC, Wadeziggg commented
P

2024-10-24 21:57 UTC, Wadeziggg commented
Well

2024-10-24 21:57 UTC, Wadeziggg commented
File

2024-10-25 20:28 UTC, Roni52-jj reviewed
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2024-10-25 20:29 UTC, Roni52-jj requested changes

2024-10-25 20:29 UTC, Roni52-jj commented on shizuku/guide/setup.md
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2024-10-25 20:29 UTC, Roni52-jj commented on shizuku/guide/setup.md
> +The Security setting "Secure app spawning" may need to be disabled.
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2024-10-27 19:17 UTC, Azzl02 approved these changes

2024-11-03 16:06 UTC, AkateMa commented
G

2024-11-06 08:47 UTC, uriyakongsangtong reviewed
Tt

2024-11-06 08:49 UTC, uriyakongsangtong reviewed
253c5c5ed5690f052c4b4635ff755f77343c4a3e

2024-11-06 17:41 UTC, MASTERARTT999 commented on shizuku/guide/setup.md
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2024-11-10 09:03 UTC, Mohyalde commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2024-11-10 09:03 UTC, Mohyalde commented
gh pr checkout 79

2024-11-13 22:31 UTC, aungko1996 commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2024-11-13 22:31 UTC, aungko1996 commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2024-11-19 17:21 UTC, xdsteven92103092 approved these changes

2024-11-19 18:22 UTC, xdsteven92103092 approved these changes

2024-11-30 23:28 UTC, Sultan12490 approved these changes

2024-12-02 03:27 UTC, Bioharzard approved these changes

2024-12-04 22:49 UTC, Blgwp21 approved these changes

2024-12-10 18:12 UTC, Blgwp21 approved these changes

2024-12-10 18:24 UTC, Sultan12490 approved these changes

2024-12-10 18:25 UTC, Sultan12490 commented on shizuku/guide/setup.md
> +The Security setting "Secure app spawning" may need to be disabled.
Q

2024-12-10 22:51 UTC, Rendicadaz commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh


@RikkaW

2024-12-13 00:50 UTC, pagentle reviewed
Danke habe ich gebraucht

2024-12-13 10:23 UTC, Blgwp21 approved these changes

2024-12-13 18:35 UTC, Sharofbe reviewed
🫀🫀

2024-12-15 22:11 UTC, xdsteven92103092 approved these changes

2024-12-19 12:08 UTC, Xjocinx commented
[](url)

2024-12-21 15:27 UTC, AungSanol commented
manager/src/main/res/mipmap-hdpi/ic_launcher.png
manager/src/main/res/mipmap-hdpi/ic_launcher_background.png
manager/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
manager/src/main/res/mipmap-xhdpi/ic_launcher.png
manager/src/main/res/mipmap-xhdpi/ic_launcher_background.png
manager/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
manager/src/main/res/mipmap-xxhdpi/ic_launcher.png
manager/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
manager/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
manager/src/main/res/mipmap-xxxhdpi/ic_launcher.png
manager/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
manager/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png

2024-12-22 13:54 UTC, manjit223 reviewed
Manjit dasare

2024-12-24 16:31 UTC, tripeasy approved these changes

2024-12-25 06:47 UTC, n1korho commented
Aaaa

2024-12-25 06:47 UTC, n1korho commented
Fhfnfnfjf

2024-12-25 06:47 UTC, n1korho commented
Ddurbxyrbhdbdydheuebrut

2024-12-25 06:47 UTC, n1korho commented
Hf dhebsudhsheuehdvdhdbrurnrurnfbfhbdhrbd

2024-12-25 22:13 UTC, gi-crypto approved these changes

2024-12-25 22:16 UTC, gi-crypto approved these changes
[]()

2024-12-27 04:35 UTC, faelin1 commented
https://github.com/RikkaAps/websites.git

2024-12-27 15:57 UTC, 65516 approved these changes

2024-12-27 23:19 UTC, Bigtrezsr77 approved these changes

2024-12-27 23:20 UTC, Bigtrezsr77 commented
Thanks[](**[]()**

2024-12-29 14:37 UTC, ozodbek457 commented
Nimaga bomyapti

2025-01-02 05:49 UTC, hu2882 commented
Ryff

2025-01-02 05:49 UTC, hu2882 commented
Tyf

2025-01-04 18:26 UTC, tacmyratsukurow commented
Salam shiziku islanok

2025-01-04 18:26 UTC, tacmyratsukurow commented
Shiziku

2025-01-04 21:16 UTC, tripeasy approved these changes

2025-01-04 21:16 UTC, tripeasy approved these changes

2025-01-05 14:07 UTC, andra723 commented
so how can i proceed

2025-01-09 13:48 UTC, mohamedkamal9918 commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-01-11 20:23 UTC, maga9099M commented
https://github.com/RikkaApps/websites.git

2025-01-22 10:12 UTC, mihsa123225 commented
Ххааха

2025-01-22 14:45 UTC, gshshef commented
تاةةللةت

2025-01-22 14:45 UTC, gshshef commented
Fhfgvff

2025-01-23 12:24 UTC, Raeeskarimullah8060 commented
https://github.com/RikkaApps/websites

2025-01-23 18:13 UTC, troublemaker420 approved these changes

2025-01-23 18:14 UTC, troublemaker420 approved these changes

2025-01-23 20:56 UTC, troublemaker420 commented
Check

2025-01-23 20:58 UTC, troublemaker420 approved these changes

2025-01-27 11:16 UTC, Deadylus requested changes
Shizuku acess

2025-01-28 08:16 UTC, KMahlaba12479 reviewed
1

2025-01-28 08:17 UTC, KMahlaba12479 requested changes
1

2025-01-30 14:12 UTC, jomararguelles3 commented
Referencing issues and pull requests

2025-01-30 14:12 UTC, jomararguelles3 commented
Referencing issues and pull requests

2025-02-01 13:17 UTC, ApollyonThaTruth approved these changes

2025-02-03 05:56 UTC, Trile9502 approved these changes

2025-02-06 07:29 UTC, ChuchinCorreao commented
Please clarify where the option "secure app spawning" is located, like is it in "Developer options" or if GrapheneOS has some standalone settings page.

2025-02-06 07:29 UTC, ChuchinCorreao commented
Please clarify where the option "secure app spawning" is located, like is it in "Developer options" or if GrapheneOS has some standalone settings page.

2025-02-09 11:20 UTC, jeyms233 commented
> Please clarify where the option "secure app spawning" is located, like is it in "Developer options" or if GrapheneOS has some standalone settings page.

Iwiq

2025-02-10 22:13 UTC, dekwan44 requested changes

2025-02-10 22:13 UTC, dekwan44 commented on shizuku/guide/setup.md
Adb sh

2025-02-14 00:43 UTC, yagramsari6556 commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2025-02-24 07:13 UTC, hhhaaammmaaaddd reviewed
Abc

2025-02-24 07:13 UTC, hhhaaammmaaaddd commented
Vbj__

2025-02-26 14:20 UTC, jeyms233 approved these changes

2025-02-27 02:58 UTC, Mo0oTta approved these changes

2025-03-05 07:29 UTC, Hajikhaksa commented on shizuku/guide/setup.md
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-03-05 07:30 UTC, Hajikhaksa commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
- [ ] in the

2025-03-07 10:51 UTC, Vovan0385 approved these changes

2025-03-07 10:55 UTC, Kvova0336 commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-03-07 18:36 UTC, Hajikhaksa reviewed
Welcome to Gboard clipboard, any text that you copy will be saved here.

2025-03-07 18:36 UTC, Hajikhaksa commented
Welcome to Gboard clipboard, any text that you copy will be saved here.

2025-03-08 00:33 UTC, 345872 approved these changes

2025-03-10 23:18 UTC, Chan72325 commented
Skizzelam

2025-03-14 01:58 UTC, mgthanwin reviewed
`7`

2025-03-19 05:49 UTC, rafiaaa456 approved these changes

2025-03-20 12:12 UTC, samanfarhan commented
djdhdndd

2025-03-20 12:13 UTC, samanfarhan commented
![FB_IMG_1741811814580](https://github.com/user-attachments/assets/90154f41-4ac7-4583-8cd7-6ad02ca4635d)

2025-03-20 17:48 UTC, dekwan44 approved these changes

2025-03-20 17:52 UTC, dekwan44 approved these changes

2025-03-20 17:53 UTC, dekwan44 approved these changes

2025-03-20 17:55 UTC, dekwan44 commented
7bbb07a0a1cadf5db1859648558160ab65b6e01f

2025-03-20 17:55 UTC, dekwan44 requested changes
/storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-03-21 21:41 UTC, rafiaaa456 approved these changes

2025-03-23 21:53 UTC, mgthanwin commented
The selected lines indicate that the file `shizuku/guide/setup.md` has been removed from the repository. The line `remove file mode` followed by the file's previous mode and the hash values confirm that the file no longer exists in the repository after this change.

2025-03-23 21:53 UTC, mgthanwin commented
Nw6437792@gmail.com

2025-04-01 02:06 UTC, Karinakeel commented on shizuku/guide/setup.md
> +The Security setting "Secure app spawning" may need to be disabled.
> shizuku/guide/setup.md

2025-04-06 18:03 UTC, mgthanwin commented
> GOS adds this setting to the main Settings > Security page. It's very obvious and presumably anyone who goes to the trouble of installing GOS knows where/what it is, or is savvy enough to do a search for it.
> 
> So would an acceptable amendment be:
> 
> > The Security setting "Secure app spawning"...
> 
> ?

့ကဩငငဂ

2025-04-06 18:04 UTC, mgthanwin commented
ကသရရ

2025-04-15 19:51 UTC, kyhtpa commented
e-t-l:patch-1

2025-04-16 11:55 UTC, freshpaint26 approved these changes

2025-04-19 07:13 UTC, Ozzy1221 approved these changes

2025-04-19 09:21 UTC, S3n3scH approved these changes
https://github.com/RikkaApps/websites/issues/493

2025-04-20 11:39 UTC, malaikha approved these changes

2025-04-21 09:38 UTC, Ozzy1221 approved these changes

2025-05-01 09:13 UTC, b4gxhjgxkg approved these changes

2025-05-01 18:20 UTC, Waham2000 requested changes
shizuku/guide/setup.md

2025-05-01 18:20 UTC, Waham2000 commented on shizuku/guide/setup.md
>  Please allow Shizuku to run in the background.
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-05-01 18:20 UTC, Waham2000 reviewed
shizuku/guide/setup.md

2025-05-02 11:36 UTC, habib772 commented
Shizuku help

2025-05-02 20:58 UTC, ulisesvera27 approved these changes

2025-05-03 06:16 UTC, Waham2000 commented
[Uploading EdXposed_Modules_20250503_090244.txt…]()

2025-05-06 10:49 UTC, Archi12345 commented
> [!NOTE]
>

2025-05-08 15:03 UTC, ulisesvera27 approved these changes

2025-05-09 01:51 UTC, tony19292992 approved these changes

2025-05-09 01:51 UTC, tony19292992 commented
Hola

2025-05-09 06:19 UTC, Wolf-bit-tech commented
https://www.coinbase.com/price/bitcoin?utm_campaign=rt_i_m_w_m_acq_ugc_soc_0_asset&utm_source=ugc&utm_platform=Android

2025-05-09 22:13 UTC, edwimjosue reviewed
Quiero usar chizuku y no puedo

2025-05-10 23:40 UTC, udeepa2001 approved these changes

2025-05-10 23:41 UTC, udeepa2001 approved these changes

2025-05-14 21:03 UTC, uchitwai approved these changes

2025-05-15 05:57 UTC, zaid007320 approved these changes

2025-05-16 09:27 UTC, udeepa2001 approved these changes

2025-05-17 02:29 UTC, udeepa2001 reviewed
shizuku/guide/setup.md

2025-05-17 02:34 UTC, udeepa2001 approved these changes

2025-05-17 19:27 UTC, fighter17185 approved these changes

2025-05-25 01:36 UTC, mohamadshahine commented
``

2025-05-25 02:53 UTC, 999-max commented
Hhholkaba

2025-05-25 02:53 UTC, 999-max commented
Hola no sirve

2025-05-26 11:46 UTC, Saddamekek commented
![Uploading 17482599920457728899579867238407.jpg…]()

2025-05-26 11:47 UTC, Saddamekek commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-05-26 11:47 UTC, Saddamekek commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-05-26 11:47 UTC, Saddamekek commented
[](url)

2025-05-27 21:08 UTC, Niheng04 approved these changes

2025-05-29 02:19 UTC, Nestorv66 reviewed
😉

2025-05-29 17:23 UTC, zaid007320 commented
```javascript

```

2025-06-01 06:59 UTC, Clawcore64 reviewed
Круто

2025-06-02 21:35 UTC, Zeldresa19 commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.



> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-06-10 14:08 UTC, yurikylekincaide06 reviewed
Lot

2025-06-10 14:08 UTC, yurikylekincaide06 commented on shizuku/guide/setup.md
> adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-06-10 14:13 UTC, yurikylekincaide06 reviewed
gh pr checkout 79

2025-06-10 14:23 UTC, yurikylekincaide06 reviewed
Revert "Update setup.md (shizuku/guide/setup.md

2025-06-14 22:46 UTC, g8a8m1b0v0i9 reviewed
shizuku/guide/setup.md

2025-06-15 02:24 UTC, Nestorv66 approved these changes

2025-06-18 14:48 UTC, yurikylekincaide06 commented
> Member

2025-06-18 14:48 UTC, yurikylekincaide06 commented
> GOS adds this setting to the main Settings > Security page. It's very obvious and presumably anyone who goes to the trouble of installing GOS knows where/what it is, or is savvy enough to do a search for it.
> 
> So would an acceptable amendment be:
> 
> > The Security setting "Secure app spawning"...
> 
> ?

2025-06-20 06:49 UTC, ggfgufcyesfii commented
> **By shizuku ** Here: ![images (1)](https://private-user-images.githubusercontent.com/133125035/251939149-b7e365fb-504a-4380-b27b-7d0bcb929c92.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTA0MDI0NDQsIm5iZiI6MTc1MDQwMjE0NCwicGF0aCI6Ii8xMzMxMjUwMzUvMjUxOTM5MTQ5LWI3ZTM2NWZiLTUwNGEtNDM4MC1iMjdiLTdkMGJjYjkyOWM5Mi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA2MjBUMDY0OTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzIyYmNjOWMwZGRhODJiZmZjZTg4ODgzZWUxODU2YzZiNDAwOGU2Y2FhNTRmOTY1MWQwZDdiMzAwMmNlYzBkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._phvACDdsnLEiLV8atu_bJWbGsuRxGyoruzcBmYr2a0)
> 
> Trwp : no Orangefox : no

2025-06-20 16:42 UTC, Ericck2711 commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-06-21 18:58 UTC, Mobinnawzad98 commented
List of devices attached
XXX      device

2025-06-21 18:59 UTC, Mobinnawzad98 commented
https://github.com/RikkaApps/websites/pull/79

2025-06-21 18:59 UTC, Mobinnawzad98 commented
https://github.com/RikkaApps/websites/pull/79

2025-06-21 19:00 UTC, Mobinnawzad98 commented
shizuku/guide/setup.md

2025-06-27 11:12 UTC, Shoaib420777 commented
How are you

2025-06-27 11:13 UTC, Shoaib420777 commented
![Snapchat-925386431](https://github.com/user-attachments/assets/04a894e6-08b8-423a-bae0-d5ad2b4c12c2)

2025-06-27 11:13 UTC, Shoaib420777 commented
My picture of free fire

2025-06-27 11:13 UTC, Shoaib420777 commented
> [`_****_`](

- [ ] Shoaib 

)

2025-06-27 11:14 UTC, Shoaib420777 commented
https://github.com/RikkaApps/websites/pull/79#issuecomment-3012642036

2025-06-27 14:46 UTC, Shoaib420777 commented
![Snapchat-925386431](https://github.com/user-attachments/assets/2b2177c2-e49b-4141-866a-924d4d0bbb51)
Thanks proxy server

2025-06-27 14:47 UTC, Shoaib420777 commented
My feeling is proxy server thanks

2025-06-27 15:07 UTC, Shoaib420777 commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-06-27 15:08 UTC, Shoaib420777 commented
![Snapchat-925386431](https://github.com/user-attachments/assets/613c472c-802c-48c2-8769-861036abcbdb)

2025-06-27 15:09 UTC, Shoaib420777 commented
### 10283842539 my account

2025-07-09 05:08 UTC, franciscograjales11 approved these changes

2025-07-09 10:06 UTC, tonspyup commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.



> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-07-11 13:37 UTC, 1593104 approved these changes

2025-07-11 15:45 UTC, jihadjaofd commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-07-11 16:34 UTC, KyawKyawtun529810 commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2025-07-11 16:49 UTC, KyawKyawtun529810 commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2025-07-11 16:56 UTC, KyawKyawtun529810 commented
https://github.com/RikkaApps/websites.git

2025-07-11 17:02 UTC, KyawKyawtun529810 commented
![Uploading Screenshot_၂၀၂၅-၀၇-၁၁-၂၀-၃၆-၄၃-၂၄၇_org.telegram.messenger.jpg…]()

2025-07-12 18:12 UTC, Rifaldi218 reviewed
![Screenshot_2025-07-12-22-43-53-48_dba69a5e82e939c3ddef13f99a115ca3](https://github.com/user-attachments/assets/ec87f017-9e44-4958-bf56-306b95f41c39)

2025-07-13 15:55 UTC, riduwanriduwan commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2025-07-13 15:55 UTC, riduwanriduwan commented
adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/start.sh

2025-07-13 15:55 UTC, riduwanriduwan commented
adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/start.sh

2025-07-13 15:55 UTC, riduwanriduwan commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2025-07-15 13:17 UTC, 1593104 reviewed
shizuku/guide/setup.md

2025-07-16 08:26 UTC, zinwine0995-cmd commented
So like

2025-07-16 08:27 UTC, zinwine0995-cmd commented
So I. like

2025-07-18 13:14 UTC, Dsjfjejekw commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
Nasıl yapiliyo valla anlamadim

2025-07-19 15:05 UTC, kusuuu01 commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-07-19 15:05 UTC, kusuuu01 commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-07-20 19:51 UTC, chandanpurty commented
Wake up original id panel

2025-07-20 19:52 UTC, chandanpurty commented
Fake ID original panel @Belu-momhn

2025-07-21 06:37 UTC, JomLeng123 commented
<a href="https://dontkillmyapp.com/oppo"><img id="badge-shareable" width="306px" src="https://dontkillmyapp.com/badge/oppo3.svg"></a>

2025-07-21 20:35 UTC, user91918739 commented
halo gays

2025-07-23 10:06 UTC, kingmadura commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
Hp Oppo a92 bisa gc

2025-07-24 11:31 UTC, hugghh5 commented
###

2025-07-24 11:31 UTC, hugghh5 commented
[Uploading bugreport-lancelot_in-QP1A.190711.020-2024-11-30-20-06-22-dumpstate_log-12051.txt…]()

2025-07-26 00:26 UTC, pkh709799-byte commented
RikkaApps#79

2025-07-26 00:27 UTC, pkh709799-byte commented
RikkaApps#79

2025-07-26 00:29 UTC, pkh709799-byte reviewed
GrapheneOS is not an officially supported ROM, but as of January 2023 Shizuku will run on it. 
@[Skizzels](https://github.com/Skizzels) Skizzels on Apr 20

2025-07-26 00:29 UTC, pkh709799-byte commented on shizuku/guide/setup.md
>  Please allow Shizuku to run in the background.
shizuku/guide/setup.md

2025-07-26 00:30 UTC, pkh709799-byte reviewed
shizuku/guide/setup.md

2025-07-26 00:31 UTC, pkh709799-byte commented
shizuku/guide/setup.md

2025-07-26 00:32 UTC, pkh709799-byte commented
e-t-l:patch-1

2025-07-26 03:44 UTC, udeepa2001 approved these changes

2025-07-29 22:30 UTC, Pediboi666 approved these changes

2025-08-01 07:17 UTC, Pappaleif94 commented on shizuku/guide/setup.md
J

2025-08-01 08:36 UTC, oceanwaveshipping02-sketch approved these changes

2025-08-01 19:01 UTC, mrfiree134-star commented
> Please clarify where the option "secure app spawning" is located, like is it in "Developer options" or if GrapheneOS has some standalone settings page.

2025-08-04 06:52 UTC, hasimjis007-tech commented
caranya gmn dah

2025-08-06 11:11 UTC, limreach23-tech commented
Ok

2025-08-07 04:45 UTC, AMIdfghj commented
infinix hot 50 Pro Plus

2025-08-07 04:45 UTC, AMIdfghj commented
Ffuugggg

2025-08-07 06:10 UTC, hhabill086-svg commented
12661159637

2025-08-07 10:42 UTC, dalidade746-hub commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
gh pr checkout 79

2025-08-08 12:11 UTC, ADB001-hub commented on shizuku/guide/setup.md
> J

2025-08-08 12:11 UTC, ADB001-hub commented on shizuku/guide/setup.md
> J

@

2025-08-08 15:21 UTC, aayanbhattarai599-web commented
### ****

2025-08-08 18:56 UTC, Three6mafia88 commented
![Screenshot_٢٠٢٥٠٨٠٨_٢١٥٣٥٤](https://github.com/user-attachments/assets/2336023e-c0a5-4ce0-8343-49e2d83bec85)
Hello, sorry that in Arabic he So for ADB

2025-08-10 18:39 UTC, magdafouadiskandar-lgtm commented
Go

2025-08-10 18:40 UTC, magdafouadiskandar-lgtm reviewed
Good

2025-08-10 18:40 UTC, magdafouadiskandar-lgtm commented on shizuku/guide/setup.md
>  Please allow Shizuku to run in the background.
Gehj

2025-08-10 18:40 UTC, magdafouadiskandar-lgtm commented
Go

2025-08-10 18:41 UTC, magdafouadiskandar-lgtm commented
Good

2025-08-11 18:36 UTC, mmly-ztn reviewed
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-08-13 18:30 UTC, buonreatt435-beep commented
https://shizuku.rikka.app/guide/setup/?night=1j

2025-08-14 14:48 UTC, aditb1155-commits commented
[Source]
[Source](https://github.com/RikkaApps/websites/pull/79#issue-1751837442https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2025-08-14 14:49 UTC, aditb1155-commits commented
[Uploading websites-master.zip…]()

2025-08-14 14:50 UTC, aditb1155-commits reviewed
https://github.com/RikkaApps/websites/pull/79/files/c76658b2a0dd06f82769a87caf546ee23ad78624#diff-204a05272ef3683a59a7395d81e61a5138d49ad2ba335f9f1e0207f9e462f0a2

2025-08-14 14:50 UTC, aditb1155-commits commented on shizuku/guide/setup.md
https://github.com/RikkaApps/websites/pull/79/files/c76658b2a0dd06f82769a87caf546ee23ad78624#diff-204a05272ef3683a59a7395d81e61a5138d49ad2ba335f9f1e0207f9e462f0a2

2025-08-15 04:11 UTC, luwangrahul260-cyber commented
Chou

2025-08-15 17:22 UTC, almubaralnalyn3-gif commented
``

2025-08-15 17:22 UTC, almubaralnalyn3-gif commented
[
Duplicate of #](url)

2025-08-17 02:43 UTC, Mkp-afg approved these changes

2025-08-19 05:51 UTC, kpwint54-cloud commented
e-t-l:patch-1

2025-08-19 09:50 UTC, bacoybiboy-glitch commented
pano mag start running yung shizuku?

2025-08-19 23:46 UTC, bagtiyarahmedow727512-commits reviewed
start

2025-08-19 23:46 UTC, bagtiyarahmedow727512-commits commented on shizuku/guide/setup.md
start

2025-08-21 08:26 UTC, rapu2645-jpg commented
> Saya telah melakukan perubahan yang dijelaskan. Mohon beri tahu saya jika perlu detail lebih lanjut (atau silakan edit frasanya sesuai kebutuhan). Beginilah pengaturannya: Jadi, cukup mudah. ![Tangkapan layar_20230615-122437_1](https://private-user-images.githubusercontent.com/40775958/247577072-1d2fdfe3-973a-4b63-8360-ae3883c11910.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU3NjUwNTQsIm5iZiI6MTc1NTc2NDc1NCwicGF0aCI6Ii80MDc3NTk1OC8yNDc1NzcwNzItMWQyZmRmZTMtOTczYS00YjYzLTgzNjAtYWUzODgzYzExOTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODIxVDA4MjU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViY2VjNjUxM2U4ZmM2Njc3MWE0OGIzMGJiYjhiNmQyNjgwZDdlMDgwNWVlMDNjNTc3Mjk3OGM0MzE2ZWQwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fjSeyXsHHvgsvQKeV1EcZA-59__JNNyw_JnIMtwx-zI)

https://github.com/RikkaApps/websites/pull/79#issuecomment-1600908117

2025-08-22 06:38 UTC, aj1926842-hue reviewed
Hjhvvkmnsnsn

2025-08-22 06:38 UTC, aj1926842-hue commented on shizuku/guide/setup.md
>  Please allow Shizuku to run in the background.
22

2025-08-22 21:40 UTC, rannlangel approved these changes

2025-08-22 21:40 UTC, rannlangel approved these changes

2025-08-23 09:47 UTC, huzaifkhan50052-collab commented
Hhdd

2025-08-24 08:37 UTC, ha0825671-afk commented
Shizuka pairing

2025-08-26 22:31 UTC, seekra13-cmyk commented
Check root access

2025-08-27 13:29 UTC, ravisivan-prog approved these changes

2025-08-29 10:26 UTC, bajdyn67-debug commented
Что это Знакомьтесь с клавиатурой Gboard! Здесь будет сохраняться текст, который вы копируете.Знакомьтесь с клавиатурой Gboard! Здесь будет сохраняться текст, который вы копируете.Знакомьтесь с клавиатурой Gboard! Здесь будет сохраняться текст, который вы копируете.Знакомьтесь с клавиатурой Gboard! Здесь будет сохраняться текст, который вы копируете.

2025-09-02 15:29 UTC, bongdop7-bit commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2025-09-02 20:01 UTC, tekaamjaitu-blip commented
https://github.com/RikkaApps/Shizuku.git

2025-09-03 15:02 UTC, mizzparker085-debug commented
Ok

2025-09-03 15:02 UTC, mizzparker085-debug commented
Mantap

2025-09-03 21:44 UTC, vedazeek999 reviewed
Kool

2025-09-03 22:21 UTC, sopheaktra11681-ops commented
[Uploading ShizukuShellLoader.java…]()

2025-09-03 22:22 UTC, sopheaktra11681-ops commented
Chou

2025-09-03 22:22 UTC, sopheaktra11681-ops commented
[ShizukuShellLoader.java](https://github.com/user-attachments/files/22127806/ShizukuShellLoader.java)

2025-09-04 04:46 UTC, Trile9502 approved these changes

2025-09-04 21:57 UTC, jesusalejandrocastaneda035-afk commented
[Sui-master.zip](https://github.com/user-attachments/files/22157819/Sui-master.zip)

2025-09-05 18:05 UTC, KyawKyawtun529810 commented
Om

၂၀၂၅၊ စက် ၅၊ သောကြာ နံနက် ၄:၂၇ တွင် jesusalejandrocastaneda035-afk <
***@***.***> က ရေးခဲ့သည်−

> *jesusalejandrocastaneda035-afk* left a comment (RikkaApps/websites#79)
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3255901590>
>
> Sui-master.zip
> <https://github.com/user-attachments/files/22157819/Sui-master.zip>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3255901590>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BUROFG2D5TXEOYCPP2IKKNT3RCYWJAVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTENJVHEYDCNJZGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-09-06 17:45 UTC, dkjmgxjvmb-ctrl commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-09-07 15:05 UTC, thelapanbelas reviewed
Very helpfull...bravo

2025-09-08 17:17 UTC, jnat75119-netizen commented
> كان تطبيق Shizuku يتوقف عن العمل بشكل عشوائي على نظام GrapheneOS (Pixel 7) رغم اتباع جميع التعليمات، وعمليات التثبيت الجديدة، وما إلى ذلك، حتى تم تعطيل إعداد الأمان الخاص بنظام Graphene "إنشاء التطبيقات الآمنة". ليسhttps://github.com/RikkaApps/websites/pull/79#issue-1751837442 من الواضح ما إذا كان هذا ضروريًا على جميع الأجهزة، ولكنه خيار جيد لمن يواجهون مشاكل.

2025-09-13 08:44 UTC, suwathnchaycanthala-star approved these changes

2025-09-14 04:36 UTC, sailocal893-ops commented
Mo

2025-09-14 19:40 UTC, ttt9tt990 approved these changes

2025-09-14 20:30 UTC, ttt9tt990 approved these changes

2025-09-18 07:40 UTC, useraditya032-ops commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2025-09-18 08:43 UTC, bhonem45635-ops commented
JdhsnanBZkdkjanzbbdbsvxbjsjhrgpljshxc

2025-09-18 14:40 UTC, m70164934-bit commented
Skin hack

2025-09-19 06:44 UTC, ttt9tt990 commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-09-19 06:44 UTC, ttt9tt990 commented
Hfj

2025-09-21 16:11 UTC, laminhtet136-star commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.
Laminhtet

2025-09-21 16:11 UTC, laminhtet136-star commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-09-21 16:11 UTC, laminhtet136-star reviewed
shizuku/guide/setup.md

2025-09-21 16:12 UTC, laminhtet136-star commented
shizuku/guide/setup.md

2025-09-21 16:14 UTC, laminhtet136-star reviewed
Laminhtet

2025-09-21 16:14 UTC, laminhtet136-star commented
> Laminhtet

Uujjjxvnlgxk

2025-09-21 16:15 UTC, laminhtet136-star commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

e-t-l:patch-1

2025-09-22 03:20 UTC, amistaddeny-cloud commented
![Uploading IMG_20250819_175532_714.webp…]()

2025-09-22 03:21 UTC, amistaddeny-cloud commented
![Uploading IMG_20250910_195052_017.jpg…]()

2025-09-22 03:21 UTC, amistaddeny-cloud commented
![IMG_20250819_175532_714](https://github.com/user-attachments/assets/d8a67761-20d1-449c-899f-ea2c90d771c0)
RHODENYSLD

2025-09-22 15:56 UTC, shavkat1234567891011-cloud commented
Annoying but you have a Barselona

2025-09-22 15:56 UTC, shavkat1234567891011-cloud commented
Hhhjiio
![Uploading IMG-20250922-WA0018.jpg…]()

2025-09-23 12:01 UTC, adgmnswr-dev commented
> GOS adds this setting to the main Settings > Security page. It's very obvious and presumably anyone who goes to the trouble of installing GOS knows where/what it is, or is savvy enough to do a search for it.
> 
> So would an acceptable amendment be:
> 
> > The Security setting "Secure app spawning"...
> 
> ?

2025

2025-09-25 07:06 UTC, thawzinhei619-ux commented
e-t-l:patch-1

2025-09-27 08:32 UTC, pp409 commented
adb shell sh /sdcard/Android/data/moe.shizuku.

2025-09-28 17:34 UTC, ttt9tt990 approved these changes

2025-09-30 05:16 UTC, ttt9tt990 reviewed
- [ ]

2025-09-30 05:17 UTC, ttt9tt990 reviewed
- [ ]

2025-10-01 13:18 UTC, soktoch1967-gif commented
Hi

2025-10-02 05:35 UTC, layl19294-coder commented
Joy

2025-10-02 05:36 UTC, layl19294-coder commented
Join

2025-10-02 17:42 UTC, ooa56261-cyber commented
Mon

2025-10-03 05:33 UTC, amiriwasiq85-maker commented
e-t-l:patch-1

2025-10-03 05:33 UTC, amiriwasiq85-maker commented
HBT

2025-10-03 07:16 UTC, amiriwasiq85-maker commented
* text=auto eol=lf

*.bat text eol=crlf
*.jar binary

2025-10-04 16:41 UTC, ajim82910-cyber commented
022400

2025-10-06 23:34 UTC, expo20999-ship-it approved these changes

2025-10-06 23:37 UTC, expo20999-ship-it approved these changes

2025-10-08 07:40 UTC, sonawnechetan03-a11y reviewed
,♥️♥️♥️♥️👍👍👍

2025-10-09 09:08 UTC, rohullaahmadzai42-commits commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

``

2025-10-09 14:57 UTC, ws180862-cloud commented
Walisson12

2025-10-09 14:57 UTC, ws180862-cloud commented
Walisson12

2025-10-09 18:32 UTC, rannlangel commented
[READ.MD](https://github.com/user-attachments/files/22803086/READ.MD)

2025-10-09 18:34 UTC, rannlangel commented
Ok 🆗 Google pixel update

2025-10-09 18:36 UTC, rannlangel reviewed
[Uploading READ.MD…]()

2025-10-09 18:36 UTC, amiriwasiq85-maker commented
بلی ها

On Thu, Oct 9, 2025, 11:05 PM Davinci Zomi ***@***.***> wrote:

> *rannlangel* left a comment (RikkaApps/websites#79)
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3387077417>
>
> Ok 🆗 Google pixel update
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3387077417>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BYHGVLVLFE6B3V5F37O56533W2TFTAVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTGOBXGA3TONBRG4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-10-10 00:01 UTC, sannaing8979-create commented
>

2025-10-10 00:02 UTC, sannaing8979-create commented
> hate Now

2025-10-10 15:08 UTC, khunpaohkham216-dev commented on shizuku/guide/setup.md
![Uploading IMG_၂၀၂၅၁၀၀၈_၁၂၁၉၄၇.jpg…]()
e-t-l:patch-1

2025-10-11 19:38 UTC, my0615576315-stack commented
> ชิซึกุจะหยุดทำงานบน GrapheneOS (Pixel 7) แบบสุ่ม แม้จะทำตามคำแนะนำทั้งหมด ติดตั้งใหม่ ฯลฯ จนกระทั่งปิดใช้งานการตั้งค่าความปลอดภัยเฉพาะของ Graphene "secure app spawn" ยังไม่ชัดเจนว่าจำเป็นต้องทำเช่นนี้กับทุกอุปกรณ์หรือไม่ แต่ถือเป็นเรื่องดีสำหรับผู้ที่กำลังประสบปัญหา

2025-10-12 00:47 UTC, eslibermejia-cpu commented
Uhnj9k

Luhk8

2025-10-12 01:42 UTC, iwayanfradythawikananda-source commented
Bagus

2025-10-12 01:43 UTC, iwayanfradythawikananda-source commented
J ad fgb

2025-10-12 02:08 UTC, khalebmail30-debug commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-10-12 02:08 UTC, khalebmail30-debug commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-10-12 22:45 UTC, ghost approved these changes

2025-10-13 15:14 UTC, emostar201511-droid commented
> Please clarify where the option "secure app spawning" is located, like is it in "Developer options" or if GrapheneOS has some standalone settings page.

2025-10-15 03:07 UTC, gghkb919-alt requested changes
adb shell sh /sdcard/Android/data/moe.shizuku.

2025-10-15 04:28 UTC, bo4127403-tech commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2025-10-15 14:31 UTC, Mon322812 approved these changes

2025-10-17 13:41 UTC, oko062508-jpg commented
SawSãw

2025-10-19 23:06 UTC, chanmyae3162-svg reviewed
![Uploading Screenshot_20250930-090204.jpg…]()

2025-10-19 23:07 UTC, chanmyae3162-svg commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-10-21 03:03 UTC, jimbasamir280-glitch commented
Thank120 esmog

2025-10-21 18:11 UTC, parayou1978 approved these changes

2025-10-22 08:34 UTC, nm3961433-cell commented
Jxidlpfzoockl

2025-10-22 08:35 UTC, nm3961433-cell commented
Oshalwj

2025-10-22 08:35 UTC, nm3961433-cell commented
nm3961433@gmail.com

2025-10-22 08:35 UTC, nm3961433-cell commented
Lwkqbwpqqjqlwapksznxbdlslsjsnspwowbsnzpzbzbxkxpdkdbspslnwaowkw

2025-10-23 07:59 UTC, yamato853853-cpu commented
e-t-l:patch-1

2025-10-23 08:16 UTC, fernandobanda0k commented
Guía

El jue, 23 de oct de 2025 2:00 a. m., yamato853853-cpu <
***@***.***> escribió:

> *yamato853853-cpu* left a comment (RikkaApps/websites#79)
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3435624838>
>
> e-t-l:patch-1
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3435624838>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BSWKIAYVO3DPTSJVRM6FX2T3ZCDLBAVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTIMZVGYZDIOBTHA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-10-23 23:07 UTC, ttt9tt990 approved these changes

2025-10-23 23:09 UTC, amiriwasiq85-maker commented
بلی ها

در تاریخ جمعه ۲۴ اکتبر ۲۰۲۵، ۳:۳۸ قبل‌ازظهر Mohammad Osman <
***@***.***> نوشت:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79#pullrequestreview-3373252292>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BYHGVLUOEQKWZFNUNGYDNXD3ZFNVRAVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZTGNZTGI2TEMRZGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-10-24 06:57 UTC, ttt9tt990 approved these changes

2025-10-24 07:31 UTC, babamskali-droid commented
Bang

2025-10-25 03:31 UTC, kgod94784-design commented
kgod94784@gmail.com

2025-10-25 03:31 UTC, kgod94784-design commented
****

2025-10-25 03:37 UTC, giovannivilleda2017-lang approved these changes

2025-10-26 06:35 UTC, giovannivilleda2017-lang approved these changes

2025-10-26 17:04 UTC, srikar10 approved these changes

2025-10-27 02:38 UTC, hsa143227-star commented
Jvvi

2025-10-27 02:38 UTC, hsa143227-star commented
![Uploading FB_IMG_1761530554463.jpg…]()

2025-10-27 02:38 UTC, hsa143227-star commented
Hh

2025-10-30 08:47 UTC, aungthann739-debug commented
Jhhhh

2025-10-30 13:39 UTC, Mon322812 approved these changes

2025-10-31 21:19 UTC, hed135 approved these changes

2025-11-01 14:05 UTC, dopp03282-code reviewed
adb shell /data/app/~~PPZVglJ2o6_lZSULV2D_iQ==/moe.shizuku.privileged.api-vgf03CWcnDYzDdO9lf6cTQ==/lib/arm64/libshizuku.so

2025-11-03 18:25 UTC, wzdfxzxguychic-blip commented
> I made the described change. Pls let me know if it needs more detail (or feel free to edit the phrasing as you see fit). This is where the setting is: ![Screenshot_20230615-122437_1](https://private-user-images.githubusercontent.com/40775958/247577072-1d2fdfe3-973a-4b63-8360-ae3883c11910.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjIxOTQ1NjAsIm5iZiI6MTc2MjE5NDI2MCwicGF0aCI6Ii80MDc3NTk1OC8yNDc1NzcwNzItMWQyZmRmZTMtOTczYS00YjYzLTgzNjAtYWUzODgzYzExOTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTAzVDE4MjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMDQ5ZWI2Njg5ZTlhNDEzOWY4Y2YxNjhhZGY1YzI5YWIyNmM0NWE2NGEyNTg2YjUzNjY1ZDhlZWZjMmI4NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7nVA7R6xSYjc2tZTsRhDerZ7nR8BvDF0k5MEakDZYa8) So it's pretty straightforward.

Gjjn

2025-11-04 00:45 UTC, jeliel07 reviewed
shizuku/guide/setup.md

2025-11-07 03:31 UTC, papuanergo-pixel commented on shizuku/guide/setup.md
>  Please allow Shizuku to run in the background.
shizuku/guide/setup.md

2025-11-07 18:00 UTC, Mon322812 commented on shizuku/guide/setup.md
>  Please allow Shizuku to run in the background.
> adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-11-09 00:01 UTC, kravabass approved these changes

2025-11-09 08:28 UTC, flashjoo587-eng commented
Shizuku my phone is not working

2025-11-09 08:28 UTC, flashjoo587-eng commented
![Uploading c2b8fdb6ec83ad93d7f4ac3cf29f850f.png…]()

2025-11-09 08:30 UTC, flashjoo587-eng commented
Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-11-09 14:15 UTC, kokaungkokaung11111-gif commented
Hello

2025-11-09 15:53 UTC, lex09845-commits approved these changes

2025-11-10 03:29 UTC, parayou1978 approved these changes

2025-11-16 15:00 UTC, hantimir1-hue reviewed
shizuku/guide/setup.md

2025-11-16 15:00 UTC, hantimir1-hue commented
shizuku/guide/setup.md

2025-11-16 15:00 UTC, hantimir1-hue commented
shizuku/guide/setup.md

2025-11-18 04:58 UTC, ahmadabdllh501 approved these changes

2025-11-18 09:50 UTC, kyawgyi5555887-rgb commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-11-18 09:51 UTC, kyawgyi5555887-rgb commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2025-11-20 12:44 UTC, la6443974-ship-it commented on shizuku/guide/setup.md
> +The Security setting "Secure app spawning" may need to be disabled.
Gfdvhffb

2025-11-20 14:10 UTC, djadhao025-hash commented
Ios

2025-11-20 14:11 UTC, djadhao025-hash commented
### **_gdgdgdy_**

2025-11-22 12:11 UTC, goutambolen867-art commented
Hi

2025-11-22 12:11 UTC, goutambolen867-art commented
Hi

2025-11-22 12:11 UTC, goutambolen867-art commented
Free fire

2025-11-22 12:11 UTC, goutambolen867-art commented
[Uploading AndroidManifest.xml…]()

2025-11-22 12:11 UTC, goutambolen867-art reviewed
Gi

2025-11-22 14:45 UTC, yeyinaungwaw1999-uxhhudi commented on shizuku/guide/setup.md
> Llugert7

Djffixfhif

2025-11-22 15:28 UTC, Mon322812 approved these changes

2025-11-23 01:28 UTC, zgksppzgkspp-sys commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
?

2025-11-23 18:29 UTC, umerygesyed-max commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
File nahin lakdi

2025-11-23 18:29 UTC, umerygesyed-max commented
File nahin lag Rahi 1 tablet

2025-11-24 16:28 UTC, bmono2106-ship-it commented on shizuku/guide/setup.md
>  Please allow Shizuku to run in the background.
storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-11-26 06:42 UTC, platafaustinoorlando-cyber reviewed
a chinga esto es nuevo

2025-11-26 06:44 UTC, platafaustinoorlando-cyber reviewed
me pueden dar contexto de esto aaaaa entonces es verdad

2025-11-26 06:45 UTC, platafaustinoorlando-cyber commented
hermano esto es lo mejor que me ha pasado

2025-11-26 15:47 UTC, ergashevabdurahim07-maker commented
Zoʻr

2025-11-26 21:32 UTC, abgysyisfogoso-maker commented
Man2man4tasskull/Stuaut/

2025-11-26 21:32 UTC, abgysyisfogoso-maker approved these changes

2025-11-27 14:59 UTC, chitpaingoo reviewed
https://github.com/RikkaApps/websites/pull/79/files/c76658b2a0dd06f82769a87caf546ee23ad78624#diff-204a05272ef3683a59a7395d81e61a5138d49ad2ba335f9f1e0207f9e462f0a2

2025-11-27 18:02 UTC, AKadisak1313 reviewed
There is nothing to preview.

2025-11-29 04:58 UTC, kevinscholl369-lab reviewed
I don't know enough this kind of code looks likre

2025-11-30 01:50 UTC, mmdym5250-rgb commented
> Please clarify where the option "secure app spawning" is located, like is it in "Developer options" or if GrapheneOS has some standalone settings page.

adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-11-30 01:50 UTC, mmdym5250-rgb commented
ل

2025-11-30 01:50 UTC, mmdym5250-rgb commented
POCO C65

2025-11-30 01:51 UTC, mmdym5250-rgb commented
ااثاپثقمخقی

2025-12-01 13:29 UTC, ongnarin reviewed
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-12-04 02:26 UTC, Danielthh approved these changes

2025-12-05 14:33 UTC, babafalak750-alt commented
Free fire

2025-12-07 10:35 UTC, emadbrahimshahen-hue commented on shizuku/guide/setup.md
>  Please allow Shizuku to run in the background.
اندرويد

2025-12-09 18:43 UTC, zeeshanahmad3366-ctrl approved these changes

2025-12-09 18:47 UTC, zeeshanahmad3366-ctrl approved these changes

2025-12-09 22:14 UTC, axelmanuelvazquez-cell commented on shizuku/guide/setup.md
> adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-12-09 22:14 UTC, Goxel-gif commented on shizuku/guide/setup.md
> adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-12-09 22:14 UTC, Goxel-gif approved these changes

2025-12-12 09:48 UTC, abgysyisfogoso-maker approved these changes

2025-12-12 15:28 UTC, mmalakasifmalakasif-eng commented
Yah problem solve karo please

2025-12-15 13:12 UTC, we5321766-ux commented
120 fps

2025-12-16 08:25 UTC, indanah536-netizen commented
Free fire Max

2025-12-16 08:26 UTC, indanah536-netizen commented
Adrian Uwete

2025-12-18 22:29 UTC, nordiccipher-pixel approved these changes

2025-12-19 07:46 UTC, azminabil51-ctrl commented
Ok

2025-12-19 07:52 UTC, kevinscholl369-lab commented
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: azminabil51-ctrl ***@***.***>
Sent: Friday, December 19, 2025 2:47:59 AM
To: RikkaApps/websites ***@***.***>
Cc: kevinscholl369-lab ***@***.***>; Comment ***@***.***>
Subject: Re: [RikkaApps/websites] Update setup.md (PR #79)

[https://avatars.githubusercontent.com/u/249325708?s=20&v=4]azminabil51-ctrl left a comment (RikkaApps/websites#79)<https://github.com/RikkaApps/websites/pull/79#issuecomment-3673964661>

Ok

—
Reply to this email directly, view it on GitHub<https://github.com/RikkaApps/websites/pull/79#issuecomment-3673964661>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/B2ZV7J2NX6S2QQ3QC6WKKTT4COUS7AVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTMNZTHE3DINRWGE>.
You are receiving this because you commented.Message ID: ***@***.***>

2025-12-19 08:04 UTC, kevinscholl369-lab commented
Thank you

________________________________
From: azminabil51-ctrl ***@***.***>
Sent: Friday, December 19, 2025 2:47:59 AM
To: RikkaApps/websites ***@***.***>
Cc: kevinscholl369-lab ***@***.***>; Comment ***@***.***>
Subject: Re: [RikkaApps/websites] Update setup.md (PR #79)

[https://avatars.githubusercontent.com/u/249325708?s=20&v=4]azminabil51-ctrl left a comment (RikkaApps/websites#79)<https://github.com/RikkaApps/websites/pull/79#issuecomment-3673964661>

Ok

—
Reply to this email directly, view it on GitHub<https://github.com/RikkaApps/websites/pull/79#issuecomment-3673964661>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/B2ZV7J2NX6S2QQ3QC6WKKTT4COUS7AVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTMNZTHE3DINRWGE>.
You are receiving this because you commented.

2025-12-20 11:30 UTC, Iydgtvot159 commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-12-22 07:09 UTC, abdullww62-design commented
Shizuku

2025-12-23 04:51 UTC, OzzieGe approved these changes

2025-12-23 04:52 UTC, OzzieRsa commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-12-23 04:52 UTC, OzzieRsa commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but it's a good thing to try for those facing trouble.

2025-12-23 04:59 UTC, febriyaniarum08-cmd commented
Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but it's a good thing to try for those facing trouble.

2025-12-24 10:36 UTC, Mon322812 approved these changes

2025-12-24 10:37 UTC, Mon322812 approved these changes

2025-12-24 14:58 UTC, aaxegod12-boop commented
> I made the described change. Pls let me know if it needs more detail (or feel free to edit the phrasing as you see fit). This is where the setting is: ![Screenshot_20230615-122437_1](https://private-user-images.githubusercontent.com/40775958/247577072-1d2fdfe3-973a-4b63-8360-ae3883c11910.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY1ODg1NDksIm5iZiI6MTc2NjU4ODI0OSwicGF0aCI6Ii80MDc3NTk1OC8yNDc1NzcwNzItMWQyZmRmZTMtOTczYS00YjYzLTgzNjAtYWUzODgzYzExOTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjI0VDE0NTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmOTk0MGYzNGU2ZWYzMzFhNmIzYmIxYWM3Yzc1YmYxMWQwOGE0NDM0Y2I3OTNiNGYwMGY1ODFiYTNmZTk4ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zu85oUj2ubaP4qYvYKoRZLRDmLlbCQTjAYa-ljXLzLI) So it's pretty straightforward.

2025-12-26 13:14 UTC, yandexpristel09-web commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-12-26 13:14 UTC, yandexpristel09-web commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-12-26 13:14 UTC, yandexpristel09-web commented
Files: SDK 36 V 361153320
OS SECURITY_PATCH:2025-11-01

2025-12-26 13:15 UTC, yandexpristel09-web commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-12-26 13:15 UTC, yandexpristel09-web commented
[adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh](url)

2025-12-27 04:06 UTC, Mon322812 approved these changes

2025-12-28 06:48 UTC, hamauk432-boop commented
List of devices attached
XXX      device
TIP

2025-12-28 23:03 UTC, Goxel-gif reviewed
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2025-12-29 05:21 UTC, ahmedfhmy56-bit commented
لم تأتي الرساله

في الأحد، ٢٨ ديسمبر ٢٠٢٥ ٨:٤٩ ص hamauk432-boop ***@***.***>
كتب:

> *hamauk432-boop* left a comment (RikkaApps/websites#79)
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3694511635>
>
> List of devices attached
> XXX device
> TIP
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3694511635>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/B2IK74BY3FZFMMKRZ6BU7W34D54O5AVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTMOJUGUYTCNRTGU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-12-29 06:56 UTC, charles16162011-spec commented
adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/start.sh

2025-12-29 18:45 UTC, 4hm4d0509-creator commented
Oy

2025-12-30 13:58 UTC, sn5777852-cyber commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

Roken

2025-12-30 13:58 UTC, sn5777852-cyber commented
![Uploading 8d32764c5b3308f4cfaa1ac991a8d4b0.jpg…]()

2025-12-30 16:42 UTC, uriyakongsangtong approved these changes

2025-12-30 19:06 UTC, zulfakkarrana7-ux commented
> **By shizuku ** Here: ![images (1)](https://private-user-images.githubusercontent.com/133125035/251939149-b7e365fb-504a-4380-b27b-7d0bcb929c92.jpeg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjcxMjE3NzUsIm5iZiI6MTc2NzEyMTQ3NSwicGF0aCI6Ii8xMzMxMjUwMzUvMjUxOTM5MTQ5LWI3ZTM2NWZiLTUwNGEtNDM4MC1iMjdiLTdkMGJjYjkyOWM5Mi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMzBUMTkwNDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Q0MTBhNGNmYzY5NWExMDUyODJlYmNhNWY4ZjMxNDM1Mjg3ZDY0MzUwYjE5YzFlOWM3ZWE2MDEwNmYzNzc3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VRNcObWij7Fki6BXmFIocZLEUpE7LCLA-FYxxhH5qgo)
> 
> Trw : no : no

2025-12-30 19:06 UTC, zulfakkarrana7-ux commented
People who are already subscribed will not be unsubscribed.

2025-12-30 19:06 UTC, zulfakkarrana7-ux commented
https://github.com/RikkaApps/websites/pull/79

2025-12-30 19:07 UTC, zulfakkarrana7-ux commented
installations

2025-12-30 19:08 UTC, zulfakkarrana7-ux commented
https://github.com/RikkaApps/websites/pull/url

2025-12-30 19:08 UTC, zulfakkarrana7-ux commented
https://github.com/RikkaApps/websites/pull/url

2025-12-30 19:08 UTC, zulfakkarrana7-ux commented
https://github.com/RikkaApps/websites/pull/3761

2025-12-30 19:09 UTC, zulfakkarrana7-ux commented
The Security setting "Secure app spawning" may need to be disabled. 
Note: GrapheneOS is not an officially supported ROM, but as of January 2023 Shizuku will run on it.

2025-12-30 20:22 UTC, zulfakkarrana7-ux commented
Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2025-12-30 20:26 UTC, zulfakkarrana7-ux commented
at rikka.shizuku.t9.n(SourceFile:12)
	at rikka.shizuku.kk.run(SourceFile:119)
	at rikka.shizuku.hz.run(SourceFile:13)
	at rikka.shizuku.om0.run(SourceFile:3)
	at rikka.shizuku.kg.l(SourceFile:1)
	at rikka.shizuku.kg$c.d(SourceFile:15)
	at rikka.shizuku.kg$c.n(SourceFile:29)

2025-12-30 20:27 UTC, zulfakkarrana7-ux commented
![Uploading Screenshot_2025-12-31-01-55-05-82_bbcac0db4b62a7ada9c32b2fb09e1801.jpg…]()

2025-12-30 20:27 UTC, zulfakkarrana7-ux commented
![Uploading Screenshot_2025-12-31-01-55-33-93_bbcac0db4b62a7ada9c32b2fb09e1801.jpg…]()

2025-12-30 20:27 UTC, zulfakkarrana7-ux commented
![Uploading Screenshot_2025-12-31-01-55-18-07_bbcac0db4b62a7ada9c32b2fb09e1801.jpg…]()

2025-12-30 20:28 UTC, zulfakkarrana7-ux commented
)
	at rikka.shizuku.t9.n(SourceFile:12)
	at rikka.shizuku.kk.run(SourceFile:119)
	at rikka.shizuku.hz.run(SourceFile:13)
	at rikka.shizuku.om0.run(SourceFile:3)
	at rikka.shizuku.kg.l(SourceFile:1)
	at rikka.shizuku.kg$c.d(SourceFile:15)
	at rikka.shizuku.kg$c.n(SourceFile:29)
	at rikka.shizuku.kg$c.run(Unknown Source:0)
Caused by: android.system.ErrnoException: connect failed: (Connection

2025-12-31 08:16 UTC, zulfakkarrana7-ux commented
private static final IPackageManager PACKAGE_MANAGER = IPackageManager.Stub.asInterface(
    new ShizukuBinderWrapper(SystemServiceHelper.getSystemSe(String packageName, String permissionName, int userId) {
    try {
        PACKAGE_MANAGER.grantRuntimePermission(;
    } catch ( tr) {
        throw new RuntimeException(tr.getMessage()

2026-01-01 19:52 UTC, Skbank83 requested changes
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2026-01-01 19:55 UTC, thetphyo20pol-source reviewed
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2026-01-02 08:37 UTC, zulfakkarrana7-ux commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
ou’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork zulfakkarrana7-ux/websites, so you can send a pull request.

2026-01-02 08:38 UTC, zulfakkarrana7-ux commented
ou’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork /websites, so you can send a pull request.

2026-01-02 08:40 UTC, zulfakkarrana7-ux commented
https://github.com/RikkaApps/websites/pull/79/files/c76658b2a0dd06f82769a87caf546ee23ad78624#diff-204a05272ef3683a59a7395d81e61a5138d49ad2ba335f9f1e0207f9e462f0a2

2026-01-02 09:08 UTC, Skbank83 approved these changes

2026-01-03 09:17 UTC, Emiliano6819 approved these changes

2026-01-06 01:11 UTC, bvfrghgg-debug commented
Hello 👋

2026-01-06 03:42 UTC, axelmanuelvazquez-cell reviewed
shizuku/guide/setup.md

2026-01-06 23:06 UTC, malikaushev099-lang reviewed
Оугугу

2026-01-07 07:58 UTC, aakashmsaakashma7-sys reviewed
Du

2026-01-07 07:58 UTC, aakashmsaakashma7-sys commented on shizuku/guide/setup.md
Ez seen hrhxh

2026-01-07 13:05 UTC, we5321766-ux commented
https://s.mobilelegends.com/CqQNCV4

2026-01-08 00:05 UTC, kolinjajk4-ctrl commented on shizuku/guide/setup.md
https://faq.whatsapp.com/1324084875126592?locale=my_MM

2026-01-08 13:09 UTC, mgmg2380652-a11y commented
R

2026-01-08 15:20 UTC, mehribanaqasova-code reviewed
Aç nolur 🙏🙏🥹

2026-01-08 15:55 UTC, kxnnxnnxy9-oss commented
[Uploading โปรแกรมคุ้มครองผู้ขายของ PayPal(1).PDF…]()

2026-01-08 15:55 UTC, kxnnxnnxy9-oss commented
kxnnxnnxy9@gmail.com

2026-01-09 11:41 UTC, delossantosakmali-creator commented
MY SHIZUKU is Not Disable My Cellphone is Oppo A3X Please Help Me

2026-01-10 10:07 UTC, mmlkn9999-creator commented
Developer options

2026-01-10 13:44 UTC, capcuttiktok205-hash reviewed
Gak bisa masukk

2026-01-10 17:52 UTC, ypoypo869-cell commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-01-11 12:34 UTC, rohi891893-lang reviewed
Starting with root...


Can't open root shell, try again...

Still not :(

2026-01-11 12:34 UTC, rohi891893-lang commented
Starting with root...


Can't open root shell, try again...

Still not :(

2026-01-11 12:34 UTC, rohi891893-lang commented
<a href="https://dontkillmyapp.com/huawei"><img id="badge-shareable" width="306px" src="https://dontkillmyapp.com/badge/huawei3.svg"></a>

2026-01-11 12:34 UTC, rohi891893-lang commented
![Uploading Free Fire MAX_2026-01-11-00-02-53.jpg…]()

2026-01-11 12:38 UTC, rnywbdalrzaq-sys commented
في الأحد، 11 جانفي 2026، 13:35 rohi891893-lang ***@***.***>
كتب:

> *rohi891893-lang* left a comment (RikkaApps/websites#79)
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3734495661>
>
> [image: Uploading Free Fire MAX_2026-01-11-00-02-53.jpg…]
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3734495661>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/B4OKM4XRLHPHCUQ6CHBFAF34GI7SPAVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTOMZUGQ4TKNRWGE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2026-01-11 16:19 UTC, kuban6016-crypto commented
👍👍

2026-01-11 16:19 UTC, kuban6016-crypto commented
### ****

2026-01-11 16:20 UTC, kuban6016-crypto commented
Wek

2026-01-12 08:13 UTC, oppo898976a-max commented
Hcnbbj

2026-01-12 12:30 UTC, bti277499-beep commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2026-01-14 02:19 UTC, conceicaokeymison-coder commented
MT bom

2026-01-14 02:19 UTC, conceicaokeymison-coder commented
Hjh

2026-01-14 02:22 UTC, tanghianrosemarie81-gif commented
sana makapag injector ako
``

2026-01-14 02:22 UTC, tanghianrosemarie81-gif commented
> ### ### _``_

2026-01-14 09:34 UTC, tae390880-code commented
Help me

2026-01-14 09:35 UTC, tae390880-code commented
private static final IPackageManager PACKAGE_MANAGER = IPackageManager.Stub.asInterface(
    new ShizukuBinderWrapper(SystemServiceHelper.getSystemService("package")));

public static void grantRuntimePermission(String packageName, String permissionName, int userId) {
    try {
        PACKAGE_MANAGER.grantRuntimePermission(packageName, permissionName, userId);
    } catch (RemoteException tr) {
        throw new RuntimeException(tr.getMessage(), tr);
    }
}

2026-01-14 11:12 UTC, aeko12032-coder commented
e-t-l:patch-1

2026-01-14 17:16 UTC, Mon322812 approved these changes

2026-01-17 01:36 UTC, kthr5763-stack commented
### 

> [`****`](url)

2026-01-20 07:17 UTC, sunnatovadilshoda5-dot commented
aggsaigsiag
ggehehehehe
ueuhhshur
hahshieeg
hehehehhee
heheheh
hehrgeirhr
hshshheieh

2026-01-22 18:27 UTC, amiriwasiq85-maker commented
بلی

در تاریخ سه‌شنبه, جنو 20, 2026،‏ 11:48 قبل‌ازظهر sunnatovadilshoda5-dot <
***@***.***> نوشت:

> *sunnatovadilshoda5-dot* left a comment (RikkaApps/websites#79)
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3771387378>
>
> aggsaigsiag
> ggehehehehe
> ueuhhshur
> hahshieeg
> hehehehhee
> heheheh
> hehrgeirhr
> hshshheieh
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-3771387378>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BYHGVLRZ6HKI24UULYFCK7T4HXJD5AVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTONZRGM4DOMZXHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2026-01-24 11:41 UTC, mnahidhamien84-ux commented
adb shell sh /sdcard/Android/data/moe.

2026-01-24 13:26 UTC, shyamdas159-lab approved these changes
Testing

2026-01-26 09:28 UTC, salihinsamporna5-commits commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
Dodokwee

2026-01-28 22:42 UTC, Baxxbanny1 approved these changes

2026-01-29 05:13 UTC, Cyclotron92 approved these changes

2026-01-30 14:22 UTC, acsiyasfi-cloud commented
تم

2026-01-30 14:27 UTC, rannlangel reviewed
adb shell sh /storage/emulated/0/Android/data/shizuku.api/start.sh

2026-01-31 01:48 UTC, letsseegoodnight reviewed
git@github.com:letsseegoodnight/letsseegoodnight.git

2026-01-31 01:48 UTC, letsseegoodnight commented
``

2026-01-31 01:49 UTC, letsseegoodnight commented
![Uploading Screenshot_2026-01-25-13-25-08-413_com.facebook.katana.jpg…]()

2026-01-31 01:49 UTC, letsseegoodnight commented
git@github.com:letsseegoodnight/letsseegoodnight.git

2026-01-31 01:49 UTC, letsseegoodnight commented
![Uploading Screenshot_2026-01-30-20-09-48-786_com.facebook.katana.jpg…]()

2026-01-31 01:49 UTC, letsseegoodnight commented
###

2026-01-31 01:49 UTC, letsseegoodnight commented
git@github.com:letsseegoodnight/letsseegoodnight.git

2026-01-31 01:50 UTC, letsseegoodnight reviewed
[``](url)

2026-01-31 01:50 UTC, letsseegoodnight commented
git@github.com:letsseegoodnight/letsseegoodnight.git

2026-01-31 20:59 UTC, pmarioher-alt commented
- ### ### [**`[](url)`**](` @ #url`)

2026-01-31 21:40 UTC, kerdeaubellebranche54-maker commented on shizuku/guide/setup.md
1xBet

2026-02-02 07:03 UTC, zaidaqeel201266-cpu reviewed
احلا تطبيق

2026-02-03 17:17 UTC, flashtm838-lab commented
https://rshrt.com/Vsr7vA7C

2026-02-06 18:22 UTC, lunkhaosei-lgtm reviewed
👍🏻

2026-02-08 22:52 UTC, ae6397586-source commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-02-08 22:53 UTC, ae6397586-source commented
Noooooo shizuku

2026-02-09 11:47 UTC, sunnatovadilshoda5-dot reviewed
Fortiori

2026-02-10 05:46 UTC, mirazmirazz8861-cmd commented
ণ্ভাই

2026-02-10 20:18 UTC, rannlangel commented
Adb shizuku.sh /sdcard/shizuka.sh
adb reboot bootloader 
![Screenshot_2026-02-10-10-21-03-97_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/05790582-a045-4335-ac28-15b64d92f151)

2026-02-11 05:52 UTC, ffmkkcc-cyber approved these changes

2026-02-11 13:45 UTC, riskipaudi5-wq reviewed
shizuku/guide/setup.md

2026-02-12 03:23 UTC, tovarolvera427-dotcom reviewed
shizuku/guide/setup.md

2026-02-12 03:24 UTC, tovarolvera427-dotcom commented
[
![Uploading IMG_20260208_174105809_BURST0020.jpg…]()
](https://github.com/RikkaApps/websites/pull/79#pullrequestreview-3788550391[](url))

2026-02-12 03:28 UTC, tovarolvera427-dotcom commented
https://github.com/RikkaApps/websites/pull/79#issuecomment-3888462558

2026-02-12 03:30 UTC, tovarolvera427-dotcom commented
> 

- [ ] 
Cabeza con
𐂂.❅ ᗰદ૨૨ʏ ᘓમ૨ıડτന੨ડ [🎅](url)
          🎊❄︎·     You are my most
     。.🎄。        wanted gift 🎁
    ❄︎🎄🎄          (ง˃̀ꄃ˂́)۶

-      🎄🎄🎄        ✉️+❤️=💌 🎄🎄🎄        ✉️+❤️=💌

    🗑        ✐.ɴɪᴄᴇ ᴅᴀʏ 〰︎🦌 

- [ ] 

> `[](url)`

          🗑        ✐.ɴɪᴄᴇ ᴅᴀʏ 〰︎🦌 
- [ ] ### _`[](url)`_

2026-02-12 05:54 UTC, attaphong126-afk commented
> > 1 `adb devices` termux or windows command prompt
> > 2 `adb (path) ` Enter
> > 3 `adb (path) cmd -l` Enter
> 
> Done!

{ADB Shell running background start with No wi-fi No-root 
  "xyChart": {
    "dataSets": [
      {
        "timeSeriesQuery": {
          "timeSeriesFilter": {
            "filter": "metric.type=\"serviceruntime.googleapis.com/api/request_count\" resource.type=\"consumed_api\" resource.label.\"service\"!=monitoring.regex.full_match(\"attaphong126@gmail.com\") metric.label.\"protocol\"=\"Adb shell running background \"",
            "aggregation": {
              "perSeriesAligner": "ALIGN_RATE",
              "crossSeriesReducer": "REDUCE_NONE",
              "groupByFields": [],
              "alignmentPeriod": "60s"
            }
          }
        },
        "plotType": "LINE",
        "targetAxis": "Y1",
        "minAlignmentPeriod": "60s"
      }
    ],
    "chartOptions": {
      "mode": "COLOR",
      "displayHorizontal": false
    },
    "thresholds": [],
    "yAxis": {
      "scale": "LINEAR"
    }
  }
}

2026-02-12 06:08 UTC, hanhtoonaing8605-glitch commented
Dh

2026-02-12 06:08 UTC, hanhtoonaing8605-glitch commented
No

2026-02-12 07:26 UTC, cipondohtangerang626-sys commented
Juli

2026-02-13 03:35 UTC, Zmei-hub approved these changes

2026-02-13 03:36 UTC, Zmei-hub commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-02-13 14:12 UTC, Zmei-hub approved these changes

2026-02-13 14:14 UTC, Zmei-hub commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-02-13 15:04 UTC, alaokfaji43-netizen commented
rbhhvzH
![Uploading IMG-20260213-WA0001.jpg…]()

2026-02-17 16:35 UTC, DrLucifer19 approved these changes

2026-02-18 17:27 UTC, matyakubovdilshad09-cmd commented
Vfxsddd

2026-02-18 17:27 UTC, matyakubovdilshad09-cmd commented
Ggfff

2026-02-20 01:33 UTC, dawtheinwin26-hash reviewed
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2026-02-20 14:46 UTC, mdsurov051-sudo reviewed
Cood deya jayna

2026-02-23 17:41 UTC, nakanonino15000-code commented
https://docs.github.com/api/article/body?pathname=/en/github-cli/github-cli/about-github-cli

2026-02-23 17:41 UTC, nakanonino15000-code commented
https://docs.github.com/api/article/body?pathname=/en/github-cli/github-cli/about-github-cli

2026-02-23 17:41 UTC, nakanonino15000-code commented
# About GitHub CLI

GitHub CLI is a command-line tool that brings pull requests, issues, GitHub Actions, and other GitHub features to your terminal, so you can do all your work in one place.

## About GitHub CLI

GitHub CLI is an open source tool for using GitHub from your computer's command line. When you're working from the command line, you can use the GitHub CLI to save time and avoid switching context.

GitHub CLI includes GitHub features such as:

* View, create, clone, and fork repositories
* Create, close, edit, and view issues and pull requests
* Review, diff, and merge pull requests
* Run, view, and list workflows
* Create, list, view, and delete releases
* Create, edit, list, view, and delete gists
* List, create, delete, and connect to a codespace
* Retrieve information from the GitHub API

For more information about what you can do with GitHub CLI, see the [GitHub CLI manual](https://cli.github.com/manual).

### What's the difference between GitHub CLI and Git on the command line?

The Git command line interface (`git`) allows you to work with a local or remote Git repository. The remote repository may be hosted on GitHub or it may be hosted by another service.

GitHub CLI (`gh`) is specifically for working with GitHub. It allows you to use the command line to interact with GitHub in all sorts of ways, as illustrated by the previous list. If you tend to work on the command line, you may prefer using GitHub CLI instead of using GitHub in a browser. GitHub CLI also makes it easier for you to create scripts to automate GitHub operations.

## Installing GitHub CLI

For installation instructions for GitHub CLI, see the [GitHub CLI repository](https://github.com/cli/cli#installation).

## Sharing feedback

If you have feedback or feature requests, you can open an issue in the [`cli/cli` repository](https://github.com/cli/cli).

2026-02-24 23:26 UTC, rodrigosantosmoreira44-dev commented
Jjh

2026-02-24 23:26 UTC, rodrigosantosmoreira44-dev commented
André

2026-02-27 02:38 UTC, bimarozani66-ai reviewed
<!-- Failed to upload "2026-02-26-213138800.mp4" -->

2026-02-27 07:39 UTC, sayagodylan023-netizen approved these changes

2026-03-04 09:57 UTC, mgnika777-create commented
Mgnika777

2026-03-04 17:15 UTC, antoniosanchezlima-png commented
Alguien que able Español para alluda con ver videos y otras app en Android  auto gracias

2026-03-07 13:35 UTC, bmmom95-ai commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2026-03-07 13:35 UTC, bmmom95-ai commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2026-03-08 15:17 UTC, dinzingoblowandzzganteng-stack commented
Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-03-08 15:21 UTC, edgarramon706-lang commented
???

El El dom, 8 mar 2026 a las 9:18 a. m., dinzingoblowandzzganteng-stack <
***@***.***> escribió:

> *dinzingoblowandzzganteng-stack* left a comment (RikkaApps/websites#79)
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-4019248015>
>
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite
> following all directions, fresh installations, etc., until the
> Graphene-specific security setting "secure app spawning" was disabled.
> Unclear if this is necessary on all devices, but is a good thing to try for
> those facing trouble.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-4019248015>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/B33THGIDFF2Z64M5P42ZCFT4PWFNDAVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHM2DAMJZGI2DQMBRGU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2026-03-11 12:49 UTC, ela03346-arch reviewed
Good

2026-03-11 12:49 UTC, ela03346-arch commented
Bb

2026-03-11 12:49 UTC, ela03346-arch commented
Good

2026-03-11 12:50 UTC, ela03346-arch commented
Soodgood

2026-03-12 16:27 UTC, amrsamaka55464-prog approved these changes

2026-03-12 16:32 UTC, amrsamaka55464-prog approved these changes

2026-03-20 03:52 UTC, ahmadrivai1990januari-boop commented
725ed7263b7df94d5c0793a8be7b2913ed9d5656

2026-03-20 03:52 UTC, ahmadrivai1990januari-boop commented
adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/start.sh

2026-03-21 10:30 UTC, mahamdmahand532-collab commented
> Please clarify where the option "secure app spawning" is located, like is it in "Developer options" or if GrapheneOS has some standalone settings page.

2026-03-21 15:10 UTC, OzzieRsa commented
Access it

2026-03-21 22:55 UTC, aofnoysoyton9 approved these changes

2026-03-22 11:25 UTC, aungkaungsatt964-tech reviewed
Zinvv tools

2026-03-22 13:58 UTC, kevinbangajhon-design commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
Anong ginagawa nyo Jan 
Wala lang bakit ano iyon

2026-03-23 12:38 UTC, cesartapia8695-collab approved these changes

2026-03-23 12:40 UTC, cesartapia8695-collab approved these changes

2026-03-23 22:14 UTC, boeainmobike-lab commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh🥰

2026-03-25 01:39 UTC, nugu09 approved these changes

2026-03-28 04:15 UTC, silva22720251-ui commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-03-28 04:15 UTC, silva22720251-ui commented
https://privacy.mi.com/all/en_US/xiaomiPrivacyPolicy.pdf

2026-03-29 17:01 UTC, saisaikharyar-jpg reviewed
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2026-03-29 18:59 UTC, saisaikharyar-jpg commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-03-31 12:55 UTC, gabbiwirewire-cpu approved these changes

2026-04-01 06:55 UTC, mikim5737-del commented
Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-04-01 07:06 UTC, mikim5737-del commented
Start Shizuku
Start with root
Start via wireless debugging
Start by connecting to a computer
FAQ
Start via wireless debugging: keeps showing "Searching for pairing service"
Start via wireless debugging: immediately fail after tapping "Enter pairing code"
Start via wireless debugging/Start by connecting to a computer: the permission of adb is limited
Start via wireless debugging/Start by connecting to a computer: Shizuku randomly stops

2026-04-02 17:37 UTC, siyovush1996 commented
> 
> Start Shizuku
> Start with root
> Start via wireless debugging
> Start by connecting to a computer
> FAQ
> Start via wireless debugging: keeps showing "Searching for pairing service"
> Start via wireless debugging: immediately fail after tapping "Enter pairing code"
> Start via wireless debugging/Start by connecting to a computer: the permission of adb is limited
> Start via wireless debugging/Start by connecting to a computer: Shizuku randomly stops
>

2026-04-02 17:56 UTC, siyovush1996 approved these changes
```

```

2026-04-02 17:56 UTC, siyovush1996 approved these changes

2026-04-02 19:08 UTC, antonrusli34-boop commented
Yyyy

2026-04-02 19:08 UTC, antonrusli34-boop commented
Ggy

2026-04-02 19:08 UTC, antonrusli34-boop commented
Gghh

2026-04-02 23:01 UTC, siyovush1996 commented
> Gghh

2026-04-02 23:08 UTC, siyovush1996 approved these changes

2026-04-02 23:11 UTC, siyovush1996 approved these changes

2026-04-02 23:11 UTC, siyovush1996 approved these changes

2026-04-05 13:05 UTC, Kwareey requested changes
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2026-04-09 17:26 UTC, Pegasus691-69 reviewed
Y

2026-04-10 04:17 UTC, davasandana-design commented
gh pr checkout 79

2026-04-10 15:54 UTC, jdjdjjdfbdjjdbd-source commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
شنو

2026-04-13 18:29 UTC, lolustomp reviewed
Commit

2026-04-14 05:00 UTC, aam1997maa-coder commented
اريد تشغيل الجذر

2026-04-14 19:36 UTC, hororchoman-cloud commented
Thanks

2026-04-15 00:02 UTC, paya07626-a11y commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2026-04-15 00:02 UTC, paya07626-a11y commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2026-04-15 00:05 UTC, paya07626-a11y commented
https://rshrt.com/e90

2026-04-15 00:06 UTC, paya07626-a11y approved these changes

2026-04-15 00:06 UTC, paya07626-a11y approved these changes
https://rshrt.com/e90

2026-04-21 07:00 UTC, errorv93-sys requested changes
Close

2026-04-24 05:51 UTC, alazaraschalew095-crypto reviewed
adb shell /data/app/~~ZDnUP-lKV-73ppYAKZ08jw==/moe.shizuku.privileged.api-d0FIcUAeY4_uGJvBiVIocw==/lib/arm64/libshizuku.so

2026-04-24 05:51 UTC, alazaraschalew095-crypto commented
gh pr checkout 79

2026-04-24 05:52 UTC, alazaraschalew095-crypto commented
🥰

2026-04-26 21:02 UTC, errorv93-sys approved these changes

2026-04-26 21:03 UTC, errorv93-sys commented
c76658b2a0dd06f82769a87caf546ee23ad78624

2026-04-26 21:04 UTC, errorv93-sys approved these changes

2026-04-28 00:59 UTC, tomekwiola2-ai approved these changes

2026-04-30 05:00 UTC, frisscillam-boop reviewed
LGN-NX1 (LGN-NX1) - HONOR 400 SMART

2026-04-30 09:25 UTC, danialsyahmi170-commits commented
gak bisa diaktifkan

2026-04-30 20:46 UTC, hlinoo470-boop reviewed
e-t-l:patch-1
Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.Please clarify where the option "secure app spawning" is located, like is it in "Developer options" or if GrapheneOS has some standalone settings page.

2026-05-02 19:31 UTC, parayou1978 approved these changes

2026-05-05 14:11 UTC, ggasaitai-lang commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-05-05 20:06 UTC, shohruzmokhmudov-sudo commented
Goooof

2026-05-05 20:06 UTC, shohruzmokhmudov-sudo commented
D

2026-05-06 16:45 UTC, aikee07 approved these changes

2026-05-07 06:24 UTC, bulbuli8590-afk reviewed
Ttteeerytwe
Nnhb mhg fee fire

2026-05-07 06:25 UTC, bulbuli8590-afk commented
Hhfg

2026-05-07 06:25 UTC, bulbuli8590-afk commented
Kbcvkij

2026-05-07 08:56 UTC, errorv93-sys reviewed
#5497 #

2026-05-07 23:09 UTC, errorv93-sys commented
#6089  #6002 #6091 #6092

2026-05-08 04:14 UTC, aikee07 commented
thanks

2026-05-08 04:15 UTC, aikee07 approved these changes

2026-05-08 04:16 UTC, aikee07 approved these changes

2026-05-08 04:16 UTC, aikee07 approved these changes

2026-05-08 05:25 UTC, MOTAZGASEM approved these changes

2026-05-08 07:20 UTC, Mon322812 approved these changes
Android 17 Beta

2026-05-10 05:03 UTC, brazilianbagus-byte reviewed
Lah

2026-05-10 10:44 UTC, rzwaheeb-debug approved these changes

2026-05-13 00:59 UTC, stevenfaelber88-png approved these changes

2026-05-13 08:28 UTC, stevenfaelber88-png approved these changes

2026-05-13 08:28 UTC, stevenfaelber88-png approved these changes

2026-05-13 11:39 UTC, stevenfaelber88-png approved these changes

2026-05-13 12:54 UTC, betomb13-3 approved these changes

2026-05-15 07:22 UTC, nashkang93-dev approved these changes

2026-05-19 12:28 UTC, parayou1978 approved these changes

2026-05-19 13:21 UTC, luonggkhanhhduyy-code commented
Helo

2026-05-20 00:11 UTC, stevenfaelber88-png approved these changes

2026-05-22 02:34 UTC, pankajinkhiya077-rgb reviewed
Yejrmntbrhjrkoe

2026-05-24 01:32 UTC, kenzujariah-a11y commented
kenzu

2026-05-24 07:17 UTC, rox-b8 approved these changes

2026-05-27 04:07 UTC, Mon322812 approved these changes
no comment

2026-05-31 21:01 UTC, stevenfaelber88-png approved these changes

2026-06-02 11:19 UTC, m96629840-blip commented
> I made the described change. Pls let me know if it needs more detail (or feel free to edit the phrasing as you see fit). This is where the setting is: ![Screenshot_20230615-122437_1](https://private-user-images.githubusercontent.com/40775958/247577072-1d2fdfe3-973a-4b63-8360-ae3883c11910.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODAzOTk0NjAsIm5iZiI6MTc4MDM5OTE2MCwicGF0aCI6Ii80MDc3NTk1OC8yNDc1NzcwNzItMWQyZmRmZTMtOTczYS00YjYzLTgzNjAtYWUzODgzYzExOTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNjAyVDExMTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0N2MwMTUzN2RmOTA1NDU5YTYwMTc1MWE3Nzk2MjRjYThjMTQ2NTBlNjQyMzBiYzg2M2MzMmU4ZGY1ZmE2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.NK4o7lObobGuJxZEcCMLyfbGgIZY2NFIRCeMpWCQy9c) So it's pretty straightforward.

2026-06-03 21:15 UTC, hendrikarim942-boop commented
com.miui.securityadd

2026-06-06 06:25 UTC, rieru0514-lang commented
Hello po

2026-06-07 05:41 UTC, zeeshanahmad3366-ctrl approved these changes
Kindly approve my request

2026-06-08 18:50 UTC, taebdaraban-commits commented
Taeb

2026-06-11 09:56 UTC, balomeconlome-cmd commented
Lời

2026-06-12 23:57 UTC, zeeshanahmad3366-ctrl approved these changes

2026-06-15 19:28 UTC, moomhanse-sys reviewed
private static final IPackageManager PACKAGE_MANAGER = IPackageManager.Stub.asInterface(
    new ShizukuBinderWrapper(SystemServiceHelper.getSystemService("package")));

public static void grantRuntimePermission(String packageName, String permissionName, int userId) {
    try {
        PACKAGE_MANAGER.grantRuntimePermission(packageName, permissionName, userId);
    } catch (RemoteException tr) {
        throw new RuntimeException(tr.getMessage(), tr);
    }
}

2026-06-16 13:44 UTC, Mon322812 commented
I'm liking 13 minute

ในวันที่ อา. 24 พ.ค. 2026 14:18 น. rox-b8 ***@***.***>
เขียนว่า:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79#pullrequestreview-4351952482>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BT24XKTCQMNJ2QXPM7XESAT44KO3FAVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHM2DGNJRHE2TENBYGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2026-06-17 12:16 UTC, bedroomeyes1290 reviewed
shizuku/guide/setup.md

2026-06-17 12:21 UTC, bedroomeyes1290 reviewed
Can i use

2026-06-22 09:25 UTC, Av3000201 approved these changes

2026-06-24 13:33 UTC, sshereenkhan262-cmyk commented
Shereenafridi

2026-06-25 03:02 UTC, adamkorsten0-ui commented
725ed7263b7df94d5c0793a8be7b2913ed9d5656

2026-06-25 03:02 UTC, adamkorsten0-ui commented
c76658b2a0dd06f82769a87caf546ee23ad78624

2026-06-25 05:33 UTC, adamkorsten0-ui commented
shizuku/guide/setup.md

2026-06-25 05:34 UTC, adamkorsten0-ui commented
shizuku/guide/setup.md

2026-06-26 05:35 UTC, jatavansh947-prog commented
Ansh

2026-06-26 05:35 UTC, jatavansh947-prog commented
Ansh

2026-06-26 05:35 UTC, jatavansh947-prog commented
Anah

2026-06-26 05:35 UTC, jatavansh947-prog commented
![Uploading IMG_20260625_065847.jpg…]()

2026-06-26 05:36 UTC, jatavansh947-prog commented
Jhbbsbsndnxnixizhsbsbbs xjzjs

2026-06-26 07:49 UTC, sshereenkhan262-cmyk commented
,,,

2026-06-26 21:03 UTC, adamkorsten0-ui commented
> shizuku/guide/setup.md

2026-06-26 23:59 UTC, farshadpixellll approved these changes

2026-06-27 00:01 UTC, farshadpixellll approved these changes

2026-06-27 00:02 UTC, farshadpixellll commented
Ok

2026-06-27 00:03 UTC, farshadpixellll approved these changes

2026-06-27 03:16 UTC, patrzyszco78-png approved these changes

2026-06-28 11:30 UTC, bedroomeyes1290 approved these changes

2026-06-28 11:31 UTC, bedroomeyes1290 approved these changes

2026-06-28 18:34 UTC, g7q3s4g7 reviewed
hashdaljmyly32@gmail.com

أداة تثبيت الحزم

2026-06-29 04:53 UTC, Laksan99 approved these changes

2026-06-29 05:15 UTC, Laksan99 approved these changes

2026-06-30 16:29 UTC, adamkorsten0-ui commented
> Ansh

    725ed7263b7df94d5c0793a8be7b2913ed9d5656

2026-06-30 16:39 UTC, mohamedkamal9918 commented
> > Ansh
> 
> ```
> 725ed7263b7df94d5c0793a8be7b2913ed9d5656
> ```

2026-06-30 16:40 UTC, mohamedkamal9918 commented
- [ ] > Ansh

    725ed7263b7df94d5c0793a8be7b2913ed9d5656

2026-07-02 09:17 UTC, jveith100-tech approved these changes

2026-07-04 11:47 UTC, chauhanshivam07789-afk commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-07-04 11:52 UTC, sshereenkhan262-cmyk commented
❤️

On Sat, 4 Jul 2026, 4:48 pm chauhanshivam07789-afk, <
***@***.***> wrote:

> *chauhanshivam07789-afk* left a comment (RikkaApps/websites#79)
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-4881860809>
>
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite
> following all directions, fresh installations, etc., until the
> Graphene-specific security setting "secure app spawning" was disabled.
> Unclear if this is necessary on all devices, but is a good thing to try for
> those facing trouble.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79?email_source=notifications&email_token=B3OA4M3SUT3VAZBUXTD7QJT5DDVIRA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTIOBYGE4DMMBYGA42M4TFMFZW63VHMNXW23LFNZ2KKZLWMVXHJLDGN5XXIZLSL5RWY2LDNM#issuecomment-4881860809>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/B3OA4M5J3OEG6CK5RGGJKUT5DDVIRAVCNFSNUABFKJSXA33TNF2G64TZHMZDAMBQGUZDQNZZHNEXG43VMU5TCNZVGE4DGNZUGQZKC5QC>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2026-07-04 18:47 UTC, aishathnolaa-ui approved these changes

2026-07-04 22:01 UTC, lyp5909-ux reviewed
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2026-07-04 22:02 UTC, lyp5909-ux commented
When you use two or more headings, GitHub

2026-07-06 06:24 UTC, virginiasofia624-bit approved these changes

2026-07-08 06:22 UTC, ryanxkeluarga-maker commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-07-08 06:22 UTC, ryanxkeluarga-maker commented
0123456789012345678901

2026-07-10 03:31 UTC, moehti383-tech reviewed
https://github.com/vvb2060/PackageInstaller.git

2026-07-10 10:30 UTC, skomar9099-lgtm reviewed
<img width="1024" height="1536" alt="Image" src="https://github.com/user-attachments/assets/701ccedc-3cd9-4019-8c48-8d1b0caa0230" />

2026-07-10 14:59 UTC, willigee313-debug commented
725ed7263b7df94d5c0793a8be7b2913ed9d5656

2026-07-11 03:56 UTC, aysha13052025-sketch approved these changes

2026-07-11 13:20 UTC, aqurshi503-maker commented
> I made the described change. Pls let me know if it needs more detail (or feel free to edit the phrasing as you see fit). This is where the setting is: ![Screenshot_20230615-122437_1](https://private-user-images.githubusercontent.com/40775958/247577072-1d2fdfe3-973a-4b63-8360-ae3883c11910.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODM3NzYyMzMsIm5iZiI6MTc4Mzc3NTkzMywicGF0aCI6Ii80MDc3NTk1OC8yNDc1NzcwNzItMWQyZmRmZTMtOTczYS00YjYzLTgzNjAtYWUzODgzYzExOTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNzExVDEzMTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MWNjYzZkYmVkMzdlNmUzZjVlMDA2MzAyYWY4Nzc4YTg5OWQ2OGRjZWEzY2E1OTg0NTkzYTBmYmQzOTE5ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.iLPTx7B7ljdsSWHiPnblxGmnNR6LrfNT2HXtW_ViI2I) So it's pretty straightforward.

2026-07-11 23:04 UTC, dkilzer7-prog approved these changes

2026-07-12 12:13 UTC, rutvikk625-ui reviewed
<script type="text/javascript" src="https://www.free-counters.org/count/jykf"></script><br>
 <a href='https://www.acadoo.de/leistungen/ghostwriter-doktorarbeit/'>Dissertation schreiben</a> <script type='text/javascript' src='https://www.whomania.com/ctr?id=57d45bf6905e1b698a18765809219e1eb5add4d2'></script>

2026-07-14 18:28 UTC, adonodorian16-pixel approved these changes

2026-07-16 02:15 UTC, altaher19900 approved these changes

2026-07-16 04:13 UTC, dkilzer7-prog approved these changes

2026-07-21 16:51 UTC, kkkahavvvggsgs-collab commented
لليظمب هي

2026-07-22 09:29 UTC, zzzeda621-ctrl commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-07-22 22:43 UTC, Mkshakal005 reviewed
Massive Warfare aftermath

2026-07-24 15:28 UTC, shahdaman011-tech reviewed
Daman ali

2026-07-26 05:27 UTC, m07885282950m-ux commented
هكر ببجي

2026-07-26 20:27 UTC, Mkshakal005 commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-07-30 05:50 UTC, pkh709799-byte commented
នៅ​ថ្ងៃទី សៅរ៍ 6 មិថុនា 2026, 1:25 PM rieru0514-lang <
***@***.***> បាន​សរសេរ​ថា៖

> *rieru0514-lang* left a comment (RikkaApps/websites#79)
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-4637669625>
>
> Hello po
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79?email_source=notifications&email_token=BVDFRVDV7W25SPGYLVYYNPT46O2PBA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTINRTG43DMOJWGI22M4TFMFZW63VHMNXW23LFNZ2KKZLWMVXHJLDGN5XXIZLSL5RWY2LDNM#issuecomment-4637669625>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BVDFRVGRPSGLT3LN66E6EN346O2PBAVCNFSM6AAAAAAZCZBMWSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHM2DMMZXGY3DSNRSGU>
> .
> Triage notifications, keep track of coding agent tasks and review pull
> requests on the go with GitHub Mobile for iOS
> <https://github.com/notifications/mobile/ios/BVDFRVBWBVTI5YPA5Q5YEUT46O2PBA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTINRTG43DMOJWGI22M4TFMFZW63VHMNXW23LFNZ2KKZLWMVXHJKTGN5XXIZLSL5UW64Y>
> and Android
> <https://github.com/notifications/mobile/android/BVDFRVD5XCMG4XVC7ZAYTLL46O2PBA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTINRTG43DMOJWGI22M4TFMFZW63VHMNXW23LFNZ2KKZLWMVXHJLTGN5XXIZLSL5QW4ZDSN5UWI>.
> Download it today!
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2026-08-02 13:13 UTC, mypaxa1488 approved these changes

2026-08-03 08:43 UTC, blackfenix07-dev approved these changes

2026-08-03 23:34 UTC, lyjfrafshar-commits approved these changes

2026-08-04 06:19 UTC, XavierMP14 reviewed
Aprove

2026-08-04 06:19 UTC, XavierMP14 reviewed
Aprove

2026-08-04 21:29 UTC, khanjan12438khan-cmyk commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-08-04 21:31 UTC, khanjan12438khan-cmyk commented
<img width="1440" height="3040" alt="Screenshot_20260805-022941" src="https://github.com/user-attachments/assets/1a15c27e-5be3-4d86-9b11-01f35c446fd1" />

2026-08-06 18:19 UTC, v6776766-lgtm commented
Vijay

2026-08-06 18:19 UTC, v6776766-lgtm commented
Vijay kumar

2026-08-06 22:01 UTC, pbg150895-beep approved these changes

2026-08-07 02:07 UTC, v6776766-lgtm commented
Vijay kumar

2026-08-07 09:47 UTC, zanllan24-spec reviewed
Llugert7

2026-08-07 09:48 UTC, zanllan24-spec reviewed
hiuy98

2026-08-10 00:59 UTC, ryanmaka0 commented
https://github.com/RikkaApps/websites/pull/79

2026-08-10 03:57 UTC, prasantnath105-oss commented
adb shell /data/app/~~la6bvn_nAW8Ry-46eVyo2w==/moe.shizuku.privileged.api-yi0fZO4yLrnC5jNwUYPBBQ==/lib/arm64/libshizuku.so

2026-08-13 02:11 UTC, tamimkakka503-wq commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-08-13 03:41 UTC, kartikod73-byte reviewed
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2026-08-13 03:42 UTC, kartikod73-byte commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2026-08-13 05:16 UTC, pbg150895-beep approved these changes

2026-08-13 09:59 UTC, hardeepsingh00403-wq reviewed
Very nice

2026-08-15 03:32 UTC, choungsun66-maker reviewed
𝗮𝗱𝗯 𝘀𝗵𝗲𝗹𝗹 𝘀𝗵 /𝘀𝘁𝗼𝗿𝗮𝗴𝗲/𝗲𝗺𝘂𝗹𝗮𝘁𝗲𝗱/𝟬/𝗔𝗻𝗱𝗿𝗼𝗶𝗱/𝗱𝗮𝘁𝗮/𝗺𝗼𝗲.𝘀𝗵𝗶𝘇𝘂𝗸𝘂.𝗽𝗿𝗶𝘃𝗶𝗹𝗲𝗴𝗲𝗱.𝗮𝗽𝗶/𝘀𝘁𝗮𝗿𝘁.𝘀𝗵

2026-08-15 10:25 UTC, Thazzbelly commented
Verify license app

2026-08-15 10:25 UTC, Thazzbelly approved these changes

2026-08-15 22:15 UTC, Ibsadhaeeyeebest approved these changes

2026-08-16 23:20 UTC, shihabewr85-cmyk reviewed
I

2026-08-16 23:36 UTC, josh2cash2-byte commented
Yo just so everybody knows this f****** thing totally put me in a boot loop and corrupted all the data on my device I had to totally reset my phone and restart

2026-08-16 23:39 UTC, 2chiefk commented
Stop deleting system primary apps that's all it is everybody

On Sun, Aug 16, 2026, 7:37 PM josh2cash2-byte ***@***.***>
wrote:

> *josh2cash2-byte* left a comment (RikkaApps/websites#79)
> <https://github.com/RikkaApps/websites/pull/79#issuecomment-5310254698>
>
> Yo just so everybody knows this f****** thing totally put me in a boot
> loop and corrupted all the data on my device I had to totally reset my
> phone and restart
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79?email_source=notifications&email_token=AYRZBWIBGWWFBBH2PFBYG4D5KJASTA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMZRGAZDKNBWHE4KM4TFMFZW63VGNVQW45LBNSSWK5TFNZ2KYZTPN52GK4S7MNWGSY3L#issuecomment-5310254698>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYRZBWL2YVVASEW3N4SCPWD5KJASTAVCNFSNUABFKJSXA33TNF2G64TZHMZDAMBQGUZDQNZZHNEXG43VMU5TCNZVGE4DGNZUGQZKC5QC>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2026-08-17 06:34 UTC, ptrdwitas-svg commented on shizuku/guide/setup.md
Abid2017

2026-08-19 19:35 UTC, josh2cash2-byte commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

What is secure app spawning (lmfao)
Ok thanks😆🤣👍🏼✌🏼

2026-08-20 15:25 UTC, mukendra5772-ctrl commented
https://github.com/RikkaApps/websites/pull/79#pullrequestreview-1848591102

2026-08-20 15:26 UTC, mukendra5772-ctrl commented
Bgmi

2026-08-22 05:22 UTC, Monemtk-cloud approved these changes

2026-08-24 01:20 UTC, Thazzbelly approved these changes

2026-08-24 01:21 UTC, Thazzbelly approved these changes

2026-08-24 15:17 UTC, l86978313-debug reviewed
# Shizuku

## Background

When developing apps that requires root, the most common method is to run some commands in the su shell. For example, there is an app that uses the `pm enable/disable` command to enable/disable components.

This method has very big disadvantages:

1. **Extremely slow** (Multiple process creation)
2. Needs to process texts (**Super unreliable**)
3. The possibility is limited to available commands
4. Even if ADB has sufficient permissions, the app requires root privileges to run

Shizuku uses a completely different way. See detailed description below.

## User guide & Download

<https://shizuku.rikka.app/>

## How does Shizuku work?

First, we need to talk about how app use system APIs. For example, if the app wants to get installed apps, we all know we should use `PackageManager#getInstalledPackages()`. This is actually an interprocess communication (IPC) process of the app process and system server process, just the Android framework did the inner works for us.

Android uses `binder` to do this type of IPC. `Binder` allows the server-side to learn the uid and pid of the client-side, so that the system server can check if the app has the permission to do the operation.

Usually, if there is a "manager" (e.g., `PackageManager`) for apps to use, there should be a "service" (e.g., `PackageManagerService`) in the system server process. We can simply think if the app holds the `binder` of the "service", it can communicate with the "service". The app process will receive binders of system services on start.

Shizuku guides users to run a process, Shizuku server, with root or ADB first. When the app starts, the `binder` to Shizuku server will also be sent to the app.

The most important feature Shizuku provides is something like be a middle man to receive requests from the app, sent them to the system server, and send back the results. You can see the `transactRemote` method in `rikka.shizuku.server.ShizukuService` class, and `moe.shizuku.api.ShizukuBinderWrapper` class for the detail.

So, we reached our goal, to use system APIs with higher permission. And to the app, it is almost identical to the use of system APIs directly.

## Developer guide

### API & sample

https://github.com/RikkaApps/Shizuku-API

### Migrating from pre-v11

> Existing applications still works, of course.

https://github.com/RikkaApps/Shizuku-API#migration-guide-for-existing-applications-use-shizuku-pre-v11

### Attention

1. ADB permissions are limited

   ADB has limited permissions and different on various system versions. You can see permissions granted to ADB [here](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/packages/Shell/AndroidManifest.xml).

   Before calling the API, you can use `ShizukuService#getUid` to check if Shizuku is running user ADB, or use `ShizukuService#checkPermission` to check if the server has sufficient permissions.

2. Hidden API limitation from Android 9

   As of Android 9, the usage of the hidden APIs is limited for normal apps. Please use other methods (such as <https://github.com/LSPosed/AndroidHiddenApiBypass>).

3. Android 8.0 & ADB

   At present, the way Shizuku service gets the app process is to combine `IActivityManager#registerProcessObserver` and `IActivityManager#registerUidObserver` (26+) to ensure that the app process will be sent when the app starts. However, on API 26, ADB lacks permissions to use `registerUidObserver`, so if you need to use Shizuku in a process that might not be started by an Activity, it is recommended to trigger the send binder by starting a transparent activity.

4. Direct use of `transactRemote` requires attention

   * The API may be different under different Android versions, please be sure to check it carefully. Also, the `android.app.IActivityManager` has the aidl form in API 26 and later, and `android.app.IActivityManager$Stub` exists only on API 26.

   * `SystemServiceHelper.getTransactionCode` may not get the correct transaction code, such as `android.content.pm.IPackageManager$Stub.TRANSACTION_getInstalledPackages` does not exist on API 25 and there is `android.content.pm.IPackageManager$Stub.TRANSACTION_getInstalledPackages_47` (this situation has been dealt with, but it is not excluded that there may be other circumstances). This problem is not encountered with the `ShizukuBinderWrapper` method.

## Developing Shizuku itself

### Build

- Clone with `git clone --recurse-submodules`
- Run gradle task `:manager:assembleDebug` or `:manager:assembleRelease`

The `:manager:assembleDebug` task generates a debuggable server. You can attach a debugger to `shizuku_server` to debug the server. Be aware that, in Android Studio, "Run/Debug configurations" - "Always install with package manager" should be checked, so that the server will use the latest code.

## License

All code files in this project are licensed under Apache 2.0

Under Apache 2.0 section 6, specifically:

* You are **FORBIDDEN** to use `manager/src/main/res/mipmap*/ic_launcher*.png` image files, unless for displaying Shizuku itself.

* You are **FORBIDDEN** to use `Shizuku` as app name or use `moe.shizuku.privileged.api` as application id or declare `moe.shizuku.manager.permission.*` permission.

2026-08-26 01:32 UTC, abdulmutalib2588-gif commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

helpt me

2026-08-26 03:26 UTC, josh2cash2-byte commented on shizuku/guide/setup.md
Nah I'm good

2026-08-26 03:26 UTC, josh2cash2-byte commented on shizuku/guide/setup.md
Nah I'm good

2026-08-28 08:02 UTC, Thazzbelly approved these changes

2026-08-28 08:02 UTC, Thazzbelly approved these changes

2026-08-30 09:36 UTC, ayanansaricr7786-boop commented
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2026-08-30 09:40 UTC, lyjfrafshar-commits approved these changes

2026-08-30 16:36 UTC, ganod4905-droid reviewed
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2026-08-31 17:39 UTC, josh2cash2-byte commented
Hit me up on Facebook I'm Josh Kash and I'll add a profile pic that is
Superman and send you the pic so you know which one I am



On Sun, Aug 30, 2026, 11:38 AM ganod4905-droid ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> adb shell sh
> /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79?email_source=notifications&email_token=CKJWYNBLDQP7WJDSFY6GP635MRJ63A5CNFSNUABKM5UWIORPF5TWS5BNNB2WEL2QOVWGYUTFOF2WK43UKJSXM2LFO4XTKMBWGEZTGNJWGM2KM4TFMFZW63VHMNXW23LFNZ2KKZLWMVXHJLDGN5XXIZLSL5RWY2LDNM#pullrequestreview-5061335634>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/CKJWYNBNWNDTRQMJEKUC6JL5MRJ63AVCNFSNUABFKJSXA33TNF2G64TZHMZDAMBQGUZDQNZZHNEXG43VMU5TCNZVGE4DGNZUGQZKC5QC>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2026-08-31 17:44 UTC, josh2cash2-byte commented
Like just calling it the way I see it okay I'm telling you straight up I
didn't delete any primary apps I didn't delete anything I wasn't supposed
to believe and I didn't delete anything that day now that I'm thinking
about it it just straight up put me in a boot loop and corrupted all my
data and I mean straight corruptedly my whole phone was f***** I had to
reset my phone and I had so much on there when it was crazy dude

On Mon, Aug 31, 2026, 12:39 PM Josh Cash ***@***.***> wrote:

> Hit me up on Facebook I'm Josh Kash and I'll add a profile pic that is
> Superman and send you the pic so you know which one I am
>
>
>
> On Sun, Aug 30, 2026, 11:38 AM ganod4905-droid ***@***.***>
> wrote:
>
>> ***@***.**** commented on this pull request.
>>
>> adb shell sh
>> /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/RikkaApps/websites/pull/79?email_source=notifications&email_token=CKJWYNBLDQP7WJDSFY6GP635MRJ63A5CNFSNUABKM5UWIORPF5TWS5BNNB2WEL2QOVWGYUTFOF2WK43UKJSXM2LFO4XTKMBWGEZTGNJWGM2KM4TFMFZW63VHMNXW23LFNZ2KKZLWMVXHJLDGN5XXIZLSL5RWY2LDNM#pullrequestreview-5061335634>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/CKJWYNBNWNDTRQMJEKUC6JL5MRJ63AVCNFSNUABFKJSXA33TNF2G64TZHMZDAMBQGUZDQNZZHNEXG43VMU5TCNZVGE4DGNZUGQZKC5QC>
>> .
>> You are receiving this because you commented.Message ID:
>> ***@***.***>
>>
>

2026-09-01 03:45 UTC, Thazzbelly approved these changes

2026-09-01 16:33 UTC, nm4019021-gif commented
> * [ ]

2026-09-01 16:33 UTC, nm4019021-gif reviewed
Koko

2026-09-01 18:08 UTC, badboybadboyb081-beep reviewed
120

2026-09-01 21:26 UTC, daniyal123gb-svg approved these changes

2026-09-02 00:13 UTC, kauam5467-design commented
Gringo xp

2026-09-02 14:55 UTC, ZoRoyell approved these changes

2026-09-03 02:15 UTC, mangubatmarkjhon7-gif reviewed
Mark jhon mangubat

2026-09-03 02:21 UTC, blackfenix07-dev reviewed
.

2026-09-03 22:16 UTC, maimuthoudam-lgtm approved these changes

2026-09-04 03:31 UTC, r82199737-dotcom commented
e-t-l:patch-1

2026-09-04 03:32 UTC, r82199737-dotcom commented
# Basic writing and formatting syntax

Create sophisticated formatting for your prose and code on GitHub with simple syntax.

## Headings

To create a heading, add one to six <kbd>#</kbd> symbols before your heading text. The number of <kbd>#</kbd> you use will determine the hierarchy level and typeface size of the heading.

```markdown
# A first-level heading
## A second-level heading
### A third-level heading
```

![Screenshot of rendered GitHub Markdown showing sample h1, h2, and h3 headers, which descend in type size and visual weight to show hierarchy level.](/assets/images/help/writing/headings-rendered.png)

When you use two or more headings, GitHub automatically generates a table of contents that you can access by clicking the "Outline" menu icon <svg version="1.1" width="16" height="16" viewBox="0 0 16 16" class="octicon octicon-list-unordered" aria-label="Table of Contents" role="img"><path d="M5.75 2.5h8.5a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5Zm0 5h8.5a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5Zm0 5h8.5a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5ZM2 14a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm1-6a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM2 4a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg> within the file header. Each heading title is listed in the table of contents and you can click a title to navigate to the selected section.

![Screenshot of a README file with the drop-down menu for the table of contents exposed. The table of contents icon is outlined in dark orange.](/assets/images/help/repository/headings-toc.png)

## Styling text

You can indicate emphasis with bold, italic, strikethrough, subscript, or superscript text in comment fields and `.md` files.

| Style                  | Syntax              | Keyboard shortcut                                                                     | Example                                  | Output                                 |                                                   |
| ---------------------- | ------------------- | ------------------------------------------------------------------------------------- | ---------------------------------------- | -------------------------------------- | ------------------------------------------------- |
| Bold                   | `** **` or `__ __`  | <kbd>Command</kbd>+<kbd>B</kbd> (Mac) or <kbd>Ctrl</kbd>+<kbd>B</kbd> (Windows/Linux) | `**This is bold text**`                  | **This is bold text**                  |                                                   |
| Italic                 | `* *` or `_ _`      | <kbd>Command</kbd>+<kbd>I</kbd> (Mac) or <kbd>Ctrl</kbd>+<kbd>I</kbd> (Windows/Linux) | `_This text is italicized_`              | *This text is italicized*              |                                                   |
| Strikethrough          | `~~ ~~` or `~ ~`    | None                                                                                  | `~~This was mistaken text~~`             | ~~This was mistaken text~~             |                                                   |
| Bold and nested italic | `** **` and `_ _`   | None                                                                                  | `**This text is _extremely_ important**` | **This text is *extremely* important** |                                                   |
| All bold and italic    | `*** ***`           | None                                                                                  | `***All this text is important***`       | ***All this text is important***       | <!-- markdownlint-disable-line emphasis-style --> |
| Subscript              | `<sub> </sub>`      | None                                                                                  | `This is a <sub>subscript</sub> text`    | This is a <sub>subscript</sub> text    |                                                   |
| Superscript            | `<sup> </sup>`      | None                                                                                  | `This is a <sup>superscript</sup> text`  | This is a <sup>superscript</sup> text  |                                                   |
| Underline              | `<ins> </ins>`      | None                                                                                  | `This is an <ins>underlined</ins> text`  | This is an <ins>underlined</ins> text  |                                                   |

## Quoting text

You can quote text with a <kbd>></kbd>.

```markdown
Text that is not a quote

> Text that is a quote
```

Quoted text is indented with a vertical line on the left and displayed using gray type.

![Screenshot of rendered GitHub Markdown showing the difference between normal and quoted text.](/assets/images/help/writing/quoted-text-rendered.png)

> \[!NOTE]
> When viewing a conversation, you can automatically quote text in a comment by highlighting the text, then typing <kbd>R</kbd>. You can quote an entire comment by clicking <svg version="1.1" width="16" height="16" viewBox="0 0 16 16" class="octicon octicon-kebab-horizontal" aria-label="The horizontal kebab icon" role="img"><path d="M8 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3ZM1.5 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Zm13 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z"></path></svg>, then **Quote reply**. For more information about keyboard shortcuts, see [Keyboard shortcuts](/en/get-started/accessibility/keyboard-shortcuts).

## Quoting code

You can call out code or a command within a sentence with single backticks. The text within the backticks will not be formatted. You can also press the <kbd>Command</kbd>+<kbd>E</kbd> (Mac) or <kbd>Ctrl</kbd>+<kbd>E</kbd> (Windows/Linux) keyboard shortcut to insert the backticks for a code block within a line of Markdown.

```markdown
Use `git status` to list all new or modified files that haven't yet been committed.
```

![Screenshot of rendered GitHub Markdown showing that characters surrounded by backticks are shown in a fixed-width typeface, highlighted in light gray.](/assets/images/help/writing/inline-code-rendered.png)

To format code or text into its own distinct block, use triple backticks.

````markdown
Some basic Git commands are:
```
git status
git add
git commit
```
````

![Screenshot of rendered GitHub Markdown showing a simple code block without syntax highlighting.](/assets/images/help/writing/code-block-rendered.png)

For more information, see [Creating and highlighting code blocks](/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

If you are frequently editing code snippets and tables, you may benefit from enabling a fixed-width font in all comment fields on GitHub. For more information, see [About writing and formatting on GitHub](/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/about-writing-and-formatting-on-github#enabling-fixed-width-fonts-in-the-editor).

## Supported color models

In issues, pull requests, and discussions, you can call out colors within a sentence by using backticks. A supported color model within backticks will display a visualization of the color.

```markdown
The background color is `#ffffff` for light mode and `#000000` for dark mode.
```

![Screenshot of rendered GitHub Markdown showing how HEX values within backticks create small circles of color, here white and then black.](/assets/images/help/writing/supported-color-models-rendered.png)

Here are the currently supported color models.

| Color | Syntax                      | Example                             | Output                                                                                                                                                                         |
| ----- | --------------------------- | ----------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
|  [...]

2026-09-04 06:24 UTC, ashiknayak690-sudo reviewed
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

2026-09-06 12:00 UTC, momimomi245677u-prog reviewed
Waw

2026-09-06 12:21 UTC, momimomi245677u-prog commented
Hhhhhhhhgghj

2026-09-07 11:39 UTC, rannlangel approved these changes

2026-09-07 12:55 UTC, b3941796-web commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
```suggestion
### Start via root: cannot start on boot
```

2026-09-08 08:25 UTC, badboybadboyb081-beep requested changes
[]()

2026-09-09 04:40 UTC, jmia53993-creator reviewed
8664

2026-09-10 09:07 UTC, peefee93 approved these changes

2026-09-10 09:08 UTC, peefee93 approved these changes

2026-09-10 14:11 UTC, Thazzbelly approved these changes

2026-09-10 14:12 UTC, Thazzbelly approved these changes

2026-09-10 14:20 UTC, peefee93 approved these changes

2026-09-11 10:28 UTC, komalkashyap0316-dev reviewed
Hello

2026-09-11 10:30 UTC, peefee93 approved these changes

2026-09-11 22:47 UTC, renaldopalines333-bit reviewed
Show moment suzuki

2026-09-12 19:51 UTC, mScott224 approved these changes

2026-09-12 19:57 UTC, ganod4905-droid commented
Hi

2026-09-12 23:39 UTC, faustocicarlli-coder commented
GG

2026-09-12 23:40 UTC, faustocicarlli-coder commented
Gg

2026-09-12 23:40 UTC, faustocicarlli-coder commented
****

2026-09-13 11:03 UTC, eividjgjh-sys reviewed
https://github.com/RikkaApps/Shizuku.git

2026-09-13 11:58 UTC, yannispeeters96 approved these changes

2026-09-13 13:18 UTC, peefee93 commented
.

2026-09-13 13:18 UTC, peefee93 approved these changes

2026-09-14 08:55 UTC, yannispeeters96 approved these changes

2026-09-15 01:21 UTC, jveith100-tech approved these changes

2026-09-15 03:03 UTC, peefee93 approved these changes

2026-09-15 03:04 UTC, peefee93 approved these changes

2026-09-15 03:04 UTC, peefee93 approved these changes

2026-09-15 03:04 UTC, peefee93 approved these changes

2026-09-15 03:04 UTC, peefee93 approved these changes

2026-09-15 03:04 UTC, peefee93 approved these changes

2026-09-15 03:04 UTC, peefee93 approved these changes

2026-09-15 03:05 UTC, peefee93 approved these changes

2026-09-15 03:06 UTC, peefee93 approved these changes

2026-09-15 18:49 UTC, peefee93 approved these changes

2026-09-15 18:53 UTC, telephoneice76-alt commented
fon162529


၂၀၂၆၊ စက် ၁၆၊ ဗုဒ္ဓဟူး ၀၁:၅၀ တွင် peefee93 ***@***.***> က
ရေးခဲ့သည်−

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79?email_source=notifications&email_token=BYON5G4KGDCNJHFMDY2TM2T5PGFNRA5CNFSNUABKM5UWIORPF5TWS5BNNB2WEL2QOVWGYUTFOF2WK43UKJSXM2LFO4XTKMRRGQ2DKMRTHA4KM4TFMFZW63VGNVQW45LBNSSWK5TFNZ2KYZTPN52GK4S7MNWGSY3L#pullrequestreview-5214452388>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BYON5G7GI4HAP7QK7XTMYPD5PGFNRAVCNFSNUABFKJSXA33TNF2G64TZHMZDAMBQGUZDQNZZHNEXG43VMU5TCNZVGE4DGNZUGQZKC5QC>
> .
> Triage notifications, keep track of coding agent tasks and review pull
> requests on the go with GitHub Mobile for iOS
> <https://github.com/notifications/mobile/ios/BYON5G5A62RROUNHVVLJ2WL5PGFNRA5CNFSNUABKM5UWIORPF5TWS5BNNB2WEL2QOVWGYUTFOF2WK43UKJSXM2LFO4XTKMRRGQ2DKMRTHA4KM4TFMFZW63VGNVQW45LBNSSWK5TFNZ2KUZTPN52GK4S7NFXXG>
> and Android
> <https://github.com/notifications/mobile/android/BYON5G5REOFKQDDOJHDWH6L5PGFNRA5CNFSNUABKM5UWIORPF5TWS5BNNB2WEL2QOVWGYUTFOF2WK43UKJSXM2LFO4XTKMRRGQ2DKMRTHA4KM4TFMFZW63VGNVQW45LBNSSWK5TFNZ2K4ZTPN52GK4S7MFXGI4TPNFSA>.
> Download it today!
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2026-09-15 19:01 UTC, peefee93 approved these changes

2026-09-15 22:33 UTC, Moydinov-ai approved these changes

2026-09-17 18:30 UTC, naanakks-ai commented
841334

2026-09-17 18:30 UTC, naanakks-ai commented
naanakks@gmail.com

2026-09-18 06:22 UTC, madoudfatollahi62768391-hue commented
> Please clarify where the option "secure app spawning" is located, like is it in "Developer options" or if GrapheneOS has some standalone settings page.

2026-09-18 06:26 UTC, peefee93 reviewed
Gg

2026-09-19 10:02 UTC, mwas51012-design reviewed
school


<img width="2448" height="3264" alt="Image" src="https://github.com/user-attachments/assets/b0226910-d135-455f-875b-7d2322b4e7b4" />

2026-09-19 21:24 UTC, JorgeMarVa approved these changes

2026-09-20 14:25 UTC, gvvvhfhfv-cloud commented
15192634440116963276

2026-09-22 08:53 UTC, rahul965521-afk commented
Realme C65 5g

2026-09-22 15:06 UTC, dikehtaw approved these changes

2026-09-24 09:28 UTC, cmoleboep-jpg commented
К

2026-09-24 15:46 UTC, plawr2236-lgtm approved these changes
apk Modil

2026-09-25 16:41 UTC, 90xxczaszaszcszzas-oss approved these changes

2026-09-26 19:03 UTC, hhhggfhhff4-lab commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2026-09-26 19:03 UTC, hhhggfhhff4-lab commented
https://github.com/RikkaApps/websites/pull/79#issue-1751837442

2026-09-26 21:51 UTC, bobbydulhao072-collab commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-09-27 10:47 UTC, rthu64345-coder approved these changes

2026-09-28 19:02 UTC, khalaka03 approved these changes

2026-09-28 19:03 UTC, khalaka03 approved these changes

2026-09-28 19:15 UTC, khalaka03 approved these changes
Kwls

2026-09-29 06:58 UTC, peefee93 approved these changes

2026-09-30 00:47 UTC, Thazzbelly approved these changes

2026-09-30 00:47 UTC, Thazzbelly commented
c76658b2a0dd06f82769a87caf546ee23ad78624

2026-09-30 00:48 UTC, Thazzbelly approved these changes

2026-09-30 14:38 UTC, joeer2556-jpg approved these changes

2026-10-01 10:31 UTC, alirezatk917-design approved these changes

2026-10-01 15:09 UTC, Pediboi666 approved these changes

2026-10-01 17:33 UTC, mukundmukund023-ai commented
Hi

2026-10-03 02:24 UTC, zok39482-blip approved these changes

2026-10-03 07:31 UTC, kakaydao729-droid approved these changes

2026-10-03 10:47 UTC, ahmeddolgiev66-tech commented on shizuku/guide/setup.md
shizuku/guide/setup.md

2026-10-03 17:48 UTC, hakilou96-sys commented
Moins le logiciel

2026-10-04 08:58 UTC, peefee93 approved these changes

2026-10-04 13:00 UTC, rrutviktarar-max commented on shizuku/guide/setup.md
Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.
e-t-l
e-t-l
authored
on Jun 12, 2023
Verified
commit
725e

2026-10-04 13:00 UTC, rrutviktarar-max approved these changes
Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.
[e-t-l](https://github.com/RikkaApps/websites/commits?author=e-t-l)
e-t-l
authored
on Jun 12, 2023
Verified
commit
[725e](https://github.com/RikkaApps/websites/commit/725ed7263b7df94d5c0793a8be7b2913ed9d5656)

2026-10-05 11:43 UTC, rinphearonn-lab approved these changes

2026-10-05 12:49 UTC, kakaydao729-droid approved these changes

2026-10-06 08:20 UTC, naunglinthuaung-creator approved these changes

2026-10-06 16:57 UTC, nimniok approved these changes

2026-10-06 17:46 UTC, joeer2556-jpg approved these changes

2026-10-06 17:47 UTC, joeer2556-jpg approved these changes

2026-10-07 00:26 UTC, frankgonzales94501-coder commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-10-07 00:26 UTC, frankgonzales94501-coder commented
Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-10-07 09:48 UTC, jerrybrown8287-lab approved these changes

2026-10-09 15:52 UTC, elopezgomez567-stack reviewed
PVP

2026-10-09 19:06 UTC, elopezgomez567-stack reviewed
022400

2026-10-09 22:17 UTC, mhswdalywsfy-droid commented
![Uploading IMG-20261002-WA0017.jpg…]()

2026-10-10 03:34 UTC, hjdkdndnjxnx-design requested changes
free free aim zhizku

2026-10-10 07:28 UTC, fieldsace85-arch approved these changes

2026-10-10 11:13 UTC, firdovsi2026-hue approved these changes

2026-10-10 12:37 UTC, topkara9949-a11y approved these changes

2026-10-11 02:11 UTC, Thazzbelly approved these changes

2026-10-11 18:39 UTC, naunglinthuaung-creator approved these changes

2026-10-12 06:23 UTC, fieldsace85-arch requested changes
[]()![Internet_20261012_010915_5.webp](https://github.com/user-attachments/assets/638678fe-4daf-4b18-8713-9d61f65ed561)

2026-10-14 21:58 UTC, yabwsalh875-sudo commented on shizuku/guide/setup.md
شسوكي يعمل ولا لا

2026-10-15 05:24 UTC, mrbeast96204-arch commented
Starting with wireless adb in port 39889...

info: starter begin
info: killing old process...
info: use apk path from argv
info: apk path is /data/app/~~Bzsn1sVHV8w__dOE_Xn0yA==/moe.shizuku.privileged.api-0TdE4ZYe4AecfY48RwfBgw==/base.apk
info: starting server...
info: shizuku_server pid is 30519
info: shizuku_starter exit with 0

Waiting for service...

2026-10-15 17:11 UTC, omarnemr206-create commented
ةل

2026-10-15 17:16 UTC, naunglinthuaung-creator commented
Thank

2026-10-15 22:15 UTC, abidsaba049209 approved these changes

2026-10-16 01:23 UTC, kesavansakthiivel-ctrl commented
![Uploading Screenshot_2026-10-16-06-53-24-044_moe.shizuku.privileged.api.jpg…]()

2026-10-16 06:01 UTC, robstroh1974 approved these changes

2026-10-17 04:50 UTC, rannlangel reviewed
Update

2026-10-17 13:55 UTC, myoheinthu2024-max approved these changes

2026-10-18 02:21 UTC, vitsa4017-prog commented
Hi

2026-10-19 18:28 UTC, yannispeeters96 commented
@copilot

2026-10-19 18:29 UTC, yannispeeters96 commented
![Uploading AISelect_20261016_125851_Creative studio.jpg…]()

2026-10-21 06:50 UTC, yasmeensmulla29-lgtm commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
adb shell /data/app/~~abMhNqVLxnSayXo5MpRX4Q==/moe.shizuku.privileged.api-JKiIflqGu5t9dk5j8IgiUA==/lib/arm64/libshizuku.so

2026-10-21 17:38 UTC, microsoft085252-spec approved these changes

2026-10-21 22:19 UTC, nimniok approved these changes

2026-10-21 22:20 UTC, nimniok approved these changes

2026-10-22 12:21 UTC, tanuki01tao-tao approved these changes

2026-10-22 21:21 UTC, Beendaud approved these changes

2026-10-23 21:56 UTC, ankitbhuriya1000-netizen commented
ankitbhuriya1000@gmail.com

2026-10-23 21:57 UTC, ankitbhuriya1000-netizen commented
Ankit Bhuriya

2026-10-24 05:27 UTC, lalod8519-stack requested changes
N

2026-10-24 06:50 UTC, xffdrvv-gif requested changes
e-t-l:patch-1

2026-10-24 06:51 UTC, xffdrvv-gif commented
e-t-l:patch-1

2026-10-24 13:14 UTC, pavzc commented
Uyt

2026-10-26 11:24 UTC, lumbrerasmolinak-dotcom commented
?

2026-10-28 18:18 UTC, yusufcokan65-debug commented
120 FPS yapma

2026-10-28 20:06 UTC, unlockrs101-crypto approved these changes

2026-10-29 12:43 UTC, khamisalsumi1-svg approved these changes

2026-10-29 12:43 UTC, khamisalsumi1-svg approved these changes

2026-10-29 14:11 UTC, tiyu007168-rgb commented
I know speak English

នៅ​ថ្ងៃទី ព្រហ 29 តុលា 2026, 7:46 PM khamisalsumi1-svg <
***@***.***> បាន​សរសេរ​ថា៖

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RikkaApps/websites/pull/79?email_source=notifications&email_token=B7GJSCDDDZVH2Z4EXU3GC335WM333A5CNFSNUABKM5UWIORPF5TWS5BNNB2WEL2QOVWGYUTFOF2WK43UKJSXM2LFO4XTKNRZG44DMMJXGI3KM4TFMFZW63VGNVQW45LBNSSWK5TFNZ2KYZTPN52GK4S7MNWGSY3L#pullrequestreview-5697861726>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/B7GJSCDFBOWMNHHILXT4INL5WM333AVCNFSNUABFKJSXA33TNF2G64TZHMZDAMBQGUZDQNZZHNEXG43VMU5TCNZVGE4DGNZUGQZKC5QC>
> .
> Triage notifications, keep track of coding agent tasks and review pull
> requests on the go with GitHub Mobile for iOS
> <https://github.com/notifications/mobile/ios/B7GJSCHZGBDSRNKW5UF5JGD5WM333A5CNFSNUABKM5UWIORPF5TWS5BNNB2WEL2QOVWGYUTFOF2WK43UKJSXM2LFO4XTKNRZG44DMMJXGI3KM4TFMFZW63VGNVQW45LBNSSWK5TFNZ2KUZTPN52GK4S7NFXXG>
> and Android
> <https://github.com/notifications/mobile/android/B7GJSCHVZQ5NP2RXUVS6R6T5WM333A5CNFSNUABKM5UWIORPF5TWS5BNNB2WEL2QOVWGYUTFOF2WK43UKJSXM2LFO4XTKNRZG44DMMJXGI3KM4TFMFZW63VGNVQW45LBNSSWK5TFNZ2K4ZTPN52GK4S7MFXGI4TPNFSA>.
> Download it today!
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2026-10-29 21:18 UTC, gezajonas26-ui approved these changes

2026-10-29 21:18 UTC, gezajonas26-ui approved these changes
FFG

2026-10-31 06:28 UTC, tianshiteluokesa-arch approved these changes

2026-10-31 07:05 UTC, alismay510-svg commented
Todo muy bien

2026-10-31 19:36 UTC, mhmd72fa-netizen reviewed
<!-- Uploading "file_00000000472c8211a0c0c3f27674f03d.png"... -->

2026-11-01 10:06 UTC, rp085449-blip commented
Hi

2026-11-02 03:54 UTC, unlockrs101-crypto approved these changes

2026-11-03 02:58 UTC, jacouch1986-stack approved these changes

2026-11-03 12:03 UTC, ppolster65-eng approved these changes

2026-11-07 01:37 UTC, MOTAZGASEM approved these changes

2026-11-07 20:35 UTC, primelight75-lang approved these changes

2026-11-08 05:38 UTC, jesussalvador1146-hue approved these changes

2026-11-08 05:38 UTC, jesussalvador1146-hue requested changes
shizuku/guide/setup.md

2026-11-08 06:29 UTC, arjygonzales32-web commented
Keren ketua

2026-11-08 15:56 UTC, unlockrs101-crypto approved these changes

2026-11-08 16:10 UTC, acuazozonchagala-afk approved these changes

2026-11-08 17:33 UTC, lullug79-dotcom commented on shizuku/guide/setup.md
>  ### Start via root: cannot start on boot
adb shell /data/app/~~WvwZOkBGWP71y5MZKPBlcw==/moe.shizuku.privileged.api-GH0W1ZJ9pu5imn2B5hU5Vw==/lib/arm64/libshizuku.so

2026-11-08 17:36 UTC, lullug79-dotcom commented on shizuku/guide/setup.md
adb shell /data/app/~~WvwZOkBGWP71y5MZKPBlcw==/moe.shizuku.privileged.api-GH0W1ZJ9pu5imn2B5hU5Vw==/lib/arm64/libshizuku.so

2026-11-10 05:45 UTC, tonet2979-creator commented
> Shizuku would randomly stop running on GrapheneOS (Pixel 7) despite following all directions, fresh installations, etc., until the Graphene-specific security setting "secure app spawning" was disabled. Unclear if this is necessary on all devices, but is a good thing to try for those facing trouble.

2026-11-10 06:17 UTC, acuazozonchagala-afk approved these changes

2026-11-10 11:39 UTC, sammim0044-code15690 approved these changes

2026-11-10 11:43 UTC, sammim0044-code15690 approved these changes

2026-11-10 21:13 UTC, yavzguldes23-creator approved these changes

2026-11-10 21:14 UTC, yavzguldes23-creator commented
gh pr checkout 79

2026-11-10 21:14 UTC, yavzguldes23-creator commented
Sınırsız uc

2026-11-10 21:14 UTC, yavzguldes23-creator commented
__

2026-11-10 21:17 UTC, yavzguldes23-creator requested changes
Sınırsız uc icin

2026-11-10 22:15 UTC, yavzguldes23-creator commented
https://github.com/RikkaApps/websites/pull/79#pullrequestreview-5849588125

2026-11-11 11:28 UTC, Pediboi666 approved these changes

2026-11-11 11:28 UTC, Pediboi666 approved these changes

2026-11-11 18:17 UTC, mcikgjtrmik-ux reviewed
e-t-l:patch-1

2026-11-12 10:28 UTC, cooperallen432-hash approved these changes

2026-11-12 12:44 UTC, abaleiabalei338-creator reviewed
adb shell /data/app/~~MSG5R12VT36apn__eogruA==/moe.shizuku.privileged.api-go_hLzJ8xqRTUapcDUPTTQ==/lib/arm64/libshizuku.so

2026-11-12 14:45 UTC, Paul9411 approved these changes

2026-11-12 17:08 UTC, ogg02 reviewed
Update setup.md (RikkaApps/websites#79)__

2026-11-13 05:13 UTC, tildaa1216-jpg approved these changes

2026-11-13 05:14 UTC, tildaa1216-jpg reviewed
Awesome

2026-11-13 05:22 UTC, mawarhi673-hue approved these changes

2026-11-14 00:03 UTC, carlosrodrigueschip200-ops approved these changes

2026-11-14 01:54 UTC, acuazozonchagala-afk approved these changes
X

2026-11-14 22:11 UTC, jemrama22-max commented
Hi

2026-11-14 22:11 UTC, jemrama22-max commented
Hi hello po salahat

2026-11-14 22:16 UTC, thecrowclub commented
Howdy

2026-11-14 22:17 UTC, thecrowclub reviewed
How is everything

2026-11-15 00:34 UTC, nicolasianmatta10-lang commented
Kaksjdkwk

2026-11-15 08:56 UTC, miaadpazouki7-dotcom approved these changes

2026-11-15 10:42 UTC, matabotond3-png approved these changes

2026-11-15 10:43 UTC, matabotond3-png commented
Bbzbz

2026-11-16 00:03 UTC, a33359509-wq reviewed
shizuku

2026-11-16 00:08 UTC, a33359509-wq reviewed
me gusta

2026-11-16 08:42 UTC, Paul9411 approved these changes

2026-11-17 07:43 UTC, jimenagomezmadrigal-cell approved these changes

2026-11-17 08:52 UTC, Pter133 approved these changes

2026-11-17 13:15 UTC, Pediboi666 approved these changes

2026-11-18 03:56 UTC, 999666m approved these changes

2026-11-18 03:56 UTC, 999666m approved these changes

2026-11-18 05:46 UTC, thakorthakormanoj95-source commented
App

2026-11-18 05:48 UTC, thakorthakormanoj95-source commented
> shizuku

2026-11-18 09:47 UTC, a9duuushsiua-eng reviewed
@yjj[]()t
5.4.276-android12-9-660570-g026a765d9ee4-ab869

2026-11-18 09:47 UTC, a9duuushsiua-eng reviewed
@yjj[]()t
5.4.276-android12-9-660570-g026a765d9ee4-ab869

2026-11-18 10:34 UTC, pyaeok23-svg requested changes
pupg

2026-11-18 16:22 UTC, Pediboi666 approved these changes

2026-11-18 16:25 UTC, Pediboi666 commented
👌

2026-11-18 16:26 UTC, Pediboi666 approved these changes

2026-11-18 22:02 UTC, 01633766049 reviewed
https://github.com/RikkaApps/websites/pull/79